unit uPSI_IdEchoUDPServer;
{
This file has been generated by UnitParser v0.7, written by M. Knight
and updated by NP. v/d Spek and George Birbilis. 
Source Code from Carlo Kok has been used to implement various sections of
UnitParser. Components of ROPS are used in the construction of UnitParser,
code implementing the class wrapper is taken from Carlo Kok's conv utility

}
interface
 
uses
   SysUtils
  ,Classes
  ,uPSComponent
  ,uPSRuntime
  ,uPSCompiler
  ;
 
type 
(*----------------------------------------------------------------------------*)
  TPSImport_IdEchoUDPServer = class(TPSPlugin)
  protected
    procedure CompileImport1(CompExec: TPSScript); override;
    procedure ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter); override;
  end;
 
 
{ compile-time registration functions }
procedure SIRegister_TIdEchoUDPServer(CL: TPSPascalCompiler);
procedure SIRegister_IdEchoUDPServer(CL: TPSPascalCompiler);

{ run-time registration functions }
procedure RIRegister_TIdEchoUDPServer(CL: TPSRuntimeClassImporter);
procedure RIRegister_IdEchoUDPServer(CL: TPSRuntimeClassImporter);

procedure Register;

implementation


uses
   IdAssignedNumbers
  ,IdSocketHandle
  ,IdUDPBase
  ,IdUDPServer
  ,IdEchoUDPServer
  ;
 
 
procedure Register;
begin
  RegisterComponents('Pascal Script', [TPSImport_IdEchoUDPServer]);
end;

(* === compile-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure SIRegister_TIdEchoUDPServer(CL: TPSPascalCompiler);
begin
  //with RegClassS(CL,'TIdUDPServer', 'TIdEchoUDPServer') do
  with CL.AddClassN(CL.FindClass('TIdUDPServer'),'TIdEchoUDPServer') do
  begin
    RegisterMethod('Constructor Create( axOwner : TComponent)');
  end;
end;

(*----------------------------------------------------------------------------*)
procedure SIRegister_IdEchoUDPServer(CL: TPSPascalCompiler);
begin
  SIRegister_TIdEchoUDPServer(CL);
end;

(* === run-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure RIRegister_TIdEchoUDPServer(CL: TPSRuntimeClassImporter);
begin
  with CL.Add(TIdEchoUDPServer) do
  begin
    RegisterConstructor(@TIdEchoUDPServer.Create, 'Create');
  end;
end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_IdEchoUDPServer(CL: TPSRuntimeClassImporter);
begin
  RIRegister_TIdEchoUDPServer(CL);
end;

 
 
{ TPSImport_IdEchoUDPServer }
(*----------------------------------------------------------------------------*)
procedure TPSImport_IdEchoUDPServer.CompileImport1(CompExec: TPSScript);
begin
  SIRegister_IdEchoUDPServer(CompExec.Comp);
end;
(*----------------------------------------------------------------------------*)
procedure TPSImport_IdEchoUDPServer.ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter);
begin
  RIRegister_IdEchoUDPServer(ri);
end;
(*----------------------------------------------------------------------------*)
 
 
end.
