unit uPSI_StDb2DBC;
{
This file has been generated by UnitParser v0.7, written by M. Knight
and updated by NP. v/d Spek and George Birbilis. 
Source Code from Carlo Kok has been used to implement various sections of
UnitParser. Components of ROPS are used in the construction of UnitParser,
code implementing the class wrapper is taken from Carlo Kok's conv utility

}
interface
 
uses
   SysUtils
  ,Classes
  ,uPSComponent
  ,uPSRuntime
  ,uPSCompiler
  ;
 
type 
(*----------------------------------------------------------------------------*)
  TPSImport_StDb2DBC = class(TPSPlugin)
  protected
    procedure CompileImport1(CompExec: TPSScript); override;
    procedure ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter); override;
  end;
 
 
{ compile-time registration functions }
procedure SIRegister_TStDbMaxiCodeBarcode(CL: TPSPascalCompiler);
procedure SIRegister_TStDbPDF417Barcode(CL: TPSPascalCompiler);
procedure SIRegister_StDb2DBC(CL: TPSPascalCompiler);

{ run-time registration functions }
procedure RIRegister_TStDbMaxiCodeBarcode(CL: TPSRuntimeClassImporter);
procedure RIRegister_TStDbPDF417Barcode(CL: TPSRuntimeClassImporter);
procedure RIRegister_StDb2DBC(CL: TPSRuntimeClassImporter);

procedure Register;

implementation


uses
   Windows
  ,Messages
  ,St2DBarC
  ,Db
  ,DbCtrls
  ,StDb2DBC
  ;
 
 
procedure Register;
begin
  RegisterComponents('Pascal Script', [TPSImport_StDb2DBC]);
end;

(* === compile-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure SIRegister_TStDbMaxiCodeBarcode(CL: TPSPascalCompiler);
begin
  //with RegClassS(CL,'TStMaxiCodeBarcode', 'TStDbMaxiCodeBarcode') do
  with CL.AddClassN(CL.FindClass('TStMaxiCodeBarcode'),'TStDbMaxiCodeBarcode') do
  begin
    RegisterMethod('Constructor Create( AOwner : TComponent)');
    RegisterProperty('CaptionDataField', 'string', iptrw);
    RegisterProperty('CarrierCountryCodeDataField', 'string', iptrw);
    RegisterProperty('CarrierPostalCodeDataField', 'string', iptrw);
    RegisterProperty('CarrierServiceClassDataField', 'string', iptrw);
    RegisterProperty('CodeDataField', 'string', iptrw);
    RegisterProperty('DataSource', 'TDataSource', iptrw);
  end;
end;

(*----------------------------------------------------------------------------*)
procedure SIRegister_TStDbPDF417Barcode(CL: TPSPascalCompiler);
begin
  //with RegClassS(CL,'TStPDF417Barcode', 'TStDbPDF417Barcode') do
  with CL.AddClassN(CL.FindClass('TStPDF417Barcode'),'TStDbPDF417Barcode') do
  begin
    RegisterMethod('Constructor Create( AOwner : TComponent)');
    RegisterProperty('CaptionDataField', 'string', iptrw);
    RegisterProperty('CodeDataField', 'string', iptrw);
    RegisterProperty('DataSource', 'TDataSource', iptrw);
  end;
end;

(*----------------------------------------------------------------------------*)
procedure SIRegister_StDb2DBC(CL: TPSPascalCompiler);
begin
  SIRegister_TStDbPDF417Barcode(CL);
  SIRegister_TStDbMaxiCodeBarcode(CL);
end;

(* === run-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure TStDbMaxiCodeBarcodeDataSource_W(Self: TStDbMaxiCodeBarcode; const T: TDataSource);
begin Self.DataSource := T; end;

(*----------------------------------------------------------------------------*)
procedure TStDbMaxiCodeBarcodeDataSource_R(Self: TStDbMaxiCodeBarcode; var T: TDataSource);
begin T := Self.DataSource; end;

(*----------------------------------------------------------------------------*)
procedure TStDbMaxiCodeBarcodeCodeDataField_W(Self: TStDbMaxiCodeBarcode; const T: string);
begin Self.CodeDataField := T; end;

(*----------------------------------------------------------------------------*)
procedure TStDbMaxiCodeBarcodeCodeDataField_R(Self: TStDbMaxiCodeBarcode; var T: string);
begin T := Self.CodeDataField; end;

(*----------------------------------------------------------------------------*)
procedure TStDbMaxiCodeBarcodeCarrierServiceClassDataField_W(Self: TStDbMaxiCodeBarcode; const T: string);
begin Self.CarrierServiceClassDataField := T; end;

(*----------------------------------------------------------------------------*)
procedure TStDbMaxiCodeBarcodeCarrierServiceClassDataField_R(Self: TStDbMaxiCodeBarcode; var T: string);
begin T := Self.CarrierServiceClassDataField; end;

(*----------------------------------------------------------------------------*)
procedure TStDbMaxiCodeBarcodeCarrierPostalCodeDataField_W(Self: TStDbMaxiCodeBarcode; const T: string);
begin Self.CarrierPostalCodeDataField := T; end;

(*----------------------------------------------------------------------------*)
procedure TStDbMaxiCodeBarcodeCarrierPostalCodeDataField_R(Self: TStDbMaxiCodeBarcode; var T: string);
begin T := Self.CarrierPostalCodeDataField; end;

(*----------------------------------------------------------------------------*)
procedure TStDbMaxiCodeBarcodeCarrierCountryCodeDataField_W(Self: TStDbMaxiCodeBarcode; const T: string);
begin Self.CarrierCountryCodeDataField := T; end;

(*----------------------------------------------------------------------------*)
procedure TStDbMaxiCodeBarcodeCarrierCountryCodeDataField_R(Self: TStDbMaxiCodeBarcode; var T: string);
begin T := Self.CarrierCountryCodeDataField; end;

(*----------------------------------------------------------------------------*)
procedure TStDbMaxiCodeBarcodeCaptionDataField_W(Self: TStDbMaxiCodeBarcode; const T: string);
begin Self.CaptionDataField := T; end;

(*----------------------------------------------------------------------------*)
procedure TStDbMaxiCodeBarcodeCaptionDataField_R(Self: TStDbMaxiCodeBarcode; var T: string);
begin T := Self.CaptionDataField; end;

(*----------------------------------------------------------------------------*)
procedure TStDbPDF417BarcodeDataSource_W(Self: TStDbPDF417Barcode; const T: TDataSource);
begin Self.DataSource := T; end;

(*----------------------------------------------------------------------------*)
procedure TStDbPDF417BarcodeDataSource_R(Self: TStDbPDF417Barcode; var T: TDataSource);
begin T := Self.DataSource; end;

(*----------------------------------------------------------------------------*)
procedure TStDbPDF417BarcodeCodeDataField_W(Self: TStDbPDF417Barcode; const T: string);
begin Self.CodeDataField := T; end;

(*----------------------------------------------------------------------------*)
procedure TStDbPDF417BarcodeCodeDataField_R(Self: TStDbPDF417Barcode; var T: string);
begin T := Self.CodeDataField; end;

(*----------------------------------------------------------------------------*)
procedure TStDbPDF417BarcodeCaptionDataField_W(Self: TStDbPDF417Barcode; const T: string);
begin Self.CaptionDataField := T; end;

(*----------------------------------------------------------------------------*)
procedure TStDbPDF417BarcodeCaptionDataField_R(Self: TStDbPDF417Barcode; var T: string);
begin T := Self.CaptionDataField; end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_TStDbMaxiCodeBarcode(CL: TPSRuntimeClassImporter);
begin
  with CL.Add(TStDbMaxiCodeBarcode) do
  begin
    RegisterConstructor(@TStDbMaxiCodeBarcode.Create, 'Create');
    RegisterPropertyHelper(@TStDbMaxiCodeBarcodeCaptionDataField_R,@TStDbMaxiCodeBarcodeCaptionDataField_W,'CaptionDataField');
    RegisterPropertyHelper(@TStDbMaxiCodeBarcodeCarrierCountryCodeDataField_R,@TStDbMaxiCodeBarcodeCarrierCountryCodeDataField_W,'CarrierCountryCodeDataField');
    RegisterPropertyHelper(@TStDbMaxiCodeBarcodeCarrierPostalCodeDataField_R,@TStDbMaxiCodeBarcodeCarrierPostalCodeDataField_W,'CarrierPostalCodeDataField');
    RegisterPropertyHelper(@TStDbMaxiCodeBarcodeCarrierServiceClassDataField_R,@TStDbMaxiCodeBarcodeCarrierServiceClassDataField_W,'CarrierServiceClassDataField');
    RegisterPropertyHelper(@TStDbMaxiCodeBarcodeCodeDataField_R,@TStDbMaxiCodeBarcodeCodeDataField_W,'CodeDataField');
    RegisterPropertyHelper(@TStDbMaxiCodeBarcodeDataSource_R,@TStDbMaxiCodeBarcodeDataSource_W,'DataSource');
  end;
end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_TStDbPDF417Barcode(CL: TPSRuntimeClassImporter);
begin
  with CL.Add(TStDbPDF417Barcode) do
  begin
    RegisterConstructor(@TStDbPDF417Barcode.Create, 'Create');
    RegisterPropertyHelper(@TStDbPDF417BarcodeCaptionDataField_R,@TStDbPDF417BarcodeCaptionDataField_W,'CaptionDataField');
    RegisterPropertyHelper(@TStDbPDF417BarcodeCodeDataField_R,@TStDbPDF417BarcodeCodeDataField_W,'CodeDataField');
    RegisterPropertyHelper(@TStDbPDF417BarcodeDataSource_R,@TStDbPDF417BarcodeDataSource_W,'DataSource');
  end;
end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_StDb2DBC(CL: TPSRuntimeClassImporter);
begin
  RIRegister_TStDbPDF417Barcode(CL);
  RIRegister_TStDbMaxiCodeBarcode(CL);
end;

 
 
{ TPSImport_StDb2DBC }
(*----------------------------------------------------------------------------*)
procedure TPSImport_StDb2DBC.CompileImport1(CompExec: TPSScript);
begin
  SIRegister_StDb2DBC(CompExec.Comp);
end;
(*----------------------------------------------------------------------------*)
procedure TPSImport_StDb2DBC.ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter);
begin
  RIRegister_StDb2DBC(ri);
end;
(*----------------------------------------------------------------------------*)
 
 
end.
