REM run the script engine all with c
REM maxbox4.exe "examples\044_queens_performer3bat.txt" para2
maxbox4.exe -c "examples\003_pas_motion.txt" 
REM maxbox4.exe -c "examples\054_pas_speakpassword3.txt"
maxbox4.exe -c "examples\080_pas_hanoi2_tester_fast_unified.txt" 
maxbox4.exe -c "examples\165_best_of_runtime3.txt" 
maxbox4.exe -c "examples\165_best_of_runtime4.txt" 
maxbox4.exe -c "examples\182_maXbook_v6.txt" 
REM maxbox4.exe -c "examples\262_mxoutputdemo5.txt" 
maxbox4.exe -c "examples\330_myclock.txt" 
maxbox4.exe -c "examples\330_myclock_vlistbox.txt"
maxbox4.exe -c "examples\336_digiclock3.txt" 
maxbox4.exe -c "examples\370_synedit2_mxtester4.txt" 
REM maxbox4.exe -c "examples\393_QRCode4.TXT" 
REM maxbox4.exe "examples\419_archimedes_spiral2.txt" 
maxbox4.exe -c "examples\452_dbtrv3accessUML3.txt" 
REM maxbox4.exe -c "examples\469_ibzresult3_timeserver7.txt" 
maxbox4.exe -c "examples\488_AsyncTerminal2.txt"
maxbox4.exe -c "examples\492_snowflake2.txt" 
maxbox4.exe -c "examples\558_hirestimer2test2.txt" 
maxbox4.exe -c "examples\575_tartaruga_desktop.txt" 
maxbox4.exe -c "examples\592_getTypeLibList.txt" 
maxbox4.exe -c "examples\598_software_list3.txt" 
REM maxbox4.exe "examples\602_moonbug.txt" 
maxbox4.exe -c "examples\602_moonbug2.txt" 
maxbox4.exe -c "examples\603_cupids_arrow.TXT"
maxbox4.exe -c "examples\604_GEOCodeReverse5.TXT" 
maxbox4.exe -c "examples\611_Arduino_COMOutputs.txt" 
maxbox4.exe -c "examples\635_bitcount_bytecodestudy2.txt" 
REM maxbox4.exe "examples\640_weather_cockpit6_1.TXT" 
maxbox4.exe -c "examples\645_age_guess_REX.pas" 
maxbox4.exe -c "examples\650_drawdice2016_3testerV4.txt" 
REM maxbox4.exe -c "examples\650_http_server2tester.txt" 
maxbox4.exe -c "examples\651_StrUtilmaxbase.pas" 
REM maxbox4.exe -c "examples\652_graph3DMainUnit2.pas"
maxbox4.exe -c "examples\653_PdoxTstbox.pas" 
maxbox4.exe -c "examples\654_spectrum_dice2016_3.txt" 
REM maxbox4.exe -c "examples\655_arduino_chess.txt" 
maxbox4.exe -c "examples\655_StIniStm.pas" 
maxbox4.exe -c "examples\656_XML_RpcCommon.pas" 
maxbox4.exe -c "examples\660_InetUtils_REST.TXT" 
maxbox4.exe -c "examples\TimeServer7Script.txt" 
REM maxbox4.exe -c "examples\652_graph3DMainUnit2.pas"
maxbox4.exe -c "examples\weatherapp3.txt" 
maxbox4.exe -c "examples\654_spectrum_dice2016_3.txt" 
REM maxbox4.exe -c "examples\655_arduino_chess.txt" 
REM maxbox4.exe "examples\scriptlist2.txt" 
maxbox4.exe -c "examples\660_InetUtils_REST.TXT" 
maxbox4.exe -c "examples\667_URobo2.pas" 
maxbox4.exe -c "examples\669_uptime.txt" 
maxbox4.exe -c "examples\670_interesting_birthday_paradox.txt"
maxbox4.exe -c "examples\1080_trend.pas" 
REM Terminate

