unit uPSI_WinInet;
{
   the last crown ot internet bone
}
interface
 
uses
   SysUtils
  ,Classes
  ,uPSComponent
  ,uPSRuntime
  ,uPSCompiler
  ;

type 
(*----------------------------------------------------------------------------*)
  TPSImport_WinInet = class(TPSPlugin)
  protected
    procedure CompileImport1(CompExec: TPSScript); override;
    procedure ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter); override;
  end;
 
 
{ compile-time registration functions }
procedure SIRegister_WinInet(CL: TPSPascalCompiler);

{ run-time registration functions }
procedure RIRegister_WinInet_Routines(S: TPSExec);

procedure Register;

implementation


uses
   Windows
  ,WinInet
  ;
 
 
procedure Register;
begin
  RegisterComponents('Pascal Script', [TPSImport_WinInet]);
end;

(* === compile-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure SIRegister_WinInet(CL: TPSPascalCompiler);
begin
  CL.AddTypeS('HINTERNET1', '___Pointer');
  CL.AddTypeS('HINTERNET', 'integer');

  //CL.AddTypeS('PHINTERNET', '^HINTERNET // will not work');
  //CL.AddTypeS('LPHINTERNET', 'PHINTERNET');
  CL.AddTypeS('INTERNET_PORT', 'Word');
  //CL.AddTypeS('PINTERNET_PORT', '^INTERNET_PORT // will not work');
  //CL.AddTypeS('LPINTERNET_PORT', 'PINTERNET_PORT');
 CL.AddConstantN('INTERNET_INVALID_PORT_NUMBER','LongInt').SetInt( 0);
 CL.AddConstantN('INTERNET_DEFAULT_FTP_PORT','LongInt').SetInt( 21);
 CL.AddConstantN('INTERNET_DEFAULT_GOPHER_PORT','LongInt').SetInt( 70);
 CL.AddConstantN('INTERNET_DEFAULT_HTTP_PORT','LongInt').SetInt( 80);
 CL.AddConstantN('INTERNET_DEFAULT_HTTPS_PORT','LongInt').SetInt( 443);
 CL.AddConstantN('INTERNET_DEFAULT_SOCKS_PORT','LongInt').SetInt( 1080);
 CL.AddConstantN('MAX_CACHE_ENTRY_INFO_SIZE','LongInt').SetInt( 4096);
 CL.AddConstantN('INTERNET_MAX_HOST_NAME_LENGTH','LongInt').SetInt( 256);
 CL.AddConstantN('INTERNET_MAX_USER_NAME_LENGTH','LongInt').SetInt( 128);
 CL.AddConstantN('INTERNET_MAX_PASSWORD_LENGTH','LongInt').SetInt( 128);
 CL.AddConstantN('INTERNET_MAX_PORT_NUMBER_LENGTH','LongInt').SetInt( 5);
 CL.AddConstantN('INTERNET_MAX_PORT_NUMBER_VALUE','LongInt').SetInt( 65535);
 CL.AddConstantN('INTERNET_MAX_PATH_LENGTH','LongInt').SetInt( 2048);
 CL.AddConstantN('INTERNET_MAX_SCHEME_LENGTH','LongInt').SetInt( 32);
 CL.AddConstantN('INTERNET_MAX_PROTOCOL_NAME','String').SetString( 'gopher');
 CL.AddConstantN('INTERNET_KEEP_ALIVE_UNKNOWN','LongInt').SetInt( - 1);
 CL.AddConstantN('INTERNET_KEEP_ALIVE_ENABLED','LongInt').SetInt( 1);
 CL.AddConstantN('INTERNET_KEEP_ALIVE_DISABLED','LongInt').SetInt( 0);
 CL.AddConstantN('INTERNET_REQFLAG_FROM_CACHE','LongWord').SetUInt( $00000001);
 CL.AddConstantN('INTERNET_REQFLAG_ASYNC','LongWord').SetUInt( $00000002);
 CL.AddConstantN('INTERNET_REQFLAG_VIA_PROXY','LongWord').SetUInt( $00000004);
 CL.AddConstantN('INTERNET_REQFLAG_NO_HEADERS','LongWord').SetUInt( $00000008);
 CL.AddConstantN('INTERNET_REQFLAG_PASSIVE','LongWord').SetUInt( $00000010);
 CL.AddConstantN('INTERNET_REQFLAG_CACHE_WRITE_DISABLED','LongWord').SetUInt( $00000040);
 CL.AddConstantN('INTERNET_FLAG_RELOAD','LongWord').SetUInt( $80000000);
 CL.AddConstantN('INTERNET_FLAG_RAW_DATA','LongWord').SetUInt( $40000000);
 CL.AddConstantN('INTERNET_FLAG_EXISTING_CONNECT','LongWord').SetUInt( $20000000);
 CL.AddConstantN('INTERNET_FLAG_ASYNC','LongWord').SetUInt( $10000000);
 CL.AddConstantN('INTERNET_FLAG_PASSIVE','LongWord').SetUInt( $08000000);
 CL.AddConstantN('INTERNET_FLAG_NO_CACHE_WRITE','LongWord').SetUInt( $04000000);
 //CL.AddConstantN('INTERNET_FLAG_DONT_CACHE','').SetString( INTERNET_FLAG_NO_CACHE_WRITE);
 CL.AddConstantN('INTERNET_FLAG_MAKE_PERSISTENT','LongWord').SetUInt( $02000000);
 CL.AddConstantN('INTERNET_FLAG_FROM_CACHE','LongWord').SetUInt( $01000000);
 CL.AddConstantN('INTERNET_FLAG_OFFLINE','LongWord').SetUInt( $01000000);
 CL.AddConstantN('INTERNET_FLAG_SECURE','LongWord').SetUInt( $00800000);
 CL.AddConstantN('INTERNET_FLAG_KEEP_CONNECTION','LongWord').SetUInt( $00400000);
 CL.AddConstantN('INTERNET_FLAG_NO_AUTO_REDIRECT','LongWord').SetUInt( $00200000);
 CL.AddConstantN('INTERNET_FLAG_READ_PREFETCH','LongWord').SetUInt( $00100000);
 CL.AddConstantN('INTERNET_FLAG_NO_COOKIES','LongWord').SetUInt( $00080000);
 CL.AddConstantN('INTERNET_FLAG_NO_AUTH','LongWord').SetUInt( $00040000);
 CL.AddConstantN('INTERNET_FLAG_CACHE_IF_NET_FAIL','LongWord').SetUInt( $00010000);
 CL.AddConstantN('INTERNET_FLAG_IGNORE_CERT_CN_INVALID','LongWord').SetUInt( $00001000);
 CL.AddConstantN('INTERNET_FLAG_IGNORE_CERT_DATE_INVALID','LongWord').SetUInt( $00002000);
 CL.AddConstantN('INTERNET_FLAG_IGNORE_REDIRECT_TO_HTTPS','LongWord').SetUInt( $00004000);
 CL.AddConstantN('INTERNET_FLAG_IGNORE_REDIRECT_TO_HTTP','LongWord').SetUInt( $00008000);
 CL.AddConstantN('INTERNET_FLAG_RESYNCHRONIZE','LongWord').SetUInt( $00000800);
 CL.AddConstantN('INTERNET_FLAG_HYPERLINK','LongWord').SetUInt( $00000400);
 CL.AddConstantN('INTERNET_FLAG_NO_UI','LongWord').SetUInt( $00000200);
 CL.AddConstantN('INTERNET_FLAG_PRAGMA_NOCACHE','LongWord').SetUInt( $00000100);
 CL.AddConstantN('INTERNET_FLAG_CACHE_ASYNC','LongWord').SetUInt( $00000080);
 CL.AddConstantN('INTERNET_FLAG_FORMS_SUBMIT','LongWord').SetUInt( $00000040);
 CL.AddConstantN('INTERNET_FLAG_NEED_FILE','LongWord').SetUInt( $00000010);
 //CL.AddConstantN('INTERNET_FLAG_MUST_CACHE_REQUEST','').SetString( INTERNET_FLAG_NEED_FILE);
 CL.AddConstantN('FTP_TRANSFER_TYPE_UNKNOWN','LongWord').SetUInt( $00000000);
 CL.AddConstantN('FTP_TRANSFER_TYPE_ASCII','LongWord').SetUInt( $00000001);
 CL.AddConstantN('FTP_TRANSFER_TYPE_BINARY','LongWord').SetUInt( $00000002);
 //CL.AddConstantN('INTERNET_FLAG_TRANSFER_ASCII','').SetString( FTP_TRANSFER_TYPE_ASCII);
 //CL.AddConstantN('INTERNET_FLAG_TRANSFER_BINARY','').SetString( FTP_TRANSFER_TYPE_BINARY);
 //CL.AddConstantN('SECURITY_SET_MASK','').SetString( SECURITY_INTERNET_MASK);
 CL.AddConstantN('INTERNET_ERROR_MASK_INSERT_CDROM','LongWord').SetUInt( $1);
 CL.AddConstantN('WININET_API_FLAG_ASYNC','LongWord').SetUInt( $00000001);
 CL.AddConstantN('WININET_API_FLAG_SYNC','LongWord').SetUInt( $00000004);
 CL.AddConstantN('WININET_API_FLAG_USE_CONTEXT','LongWord').SetUInt( $00000008);
 CL.AddConstantN('INTERNET_NO_CALLBACK','LongInt').SetInt( 0);
  //CL.AddTypeS('PInternetScheme', '^TInternetScheme // will not work');
  CL.AddTypeS('TInternetScheme', 'Integer');
 CL.AddConstantN('INTERNET_SCHEME_PARTIAL','LongInt').SetInt( - 2);
 CL.AddConstantN('INTERNET_SCHEME_UNKNOWN','LongInt').SetInt( - 1);
 CL.AddConstantN('INTERNET_SCHEME_DEFAULT','LongInt').SetInt( 0);
 CL.AddConstantN('INTERNET_SCHEME_FTP','LongInt').SetInt( 1);
 CL.AddConstantN('INTERNET_SCHEME_GOPHER','LongInt').SetInt( 2);
 CL.AddConstantN('INTERNET_SCHEME_HTTP','LongInt').SetInt( 3);
 CL.AddConstantN('INTERNET_SCHEME_HTTPS','LongInt').SetInt( 4);
 CL.AddConstantN('INTERNET_SCHEME_FILE','LongInt').SetInt( 5);
 CL.AddConstantN('INTERNET_SCHEME_NEWS','LongInt').SetInt( 6);
 CL.AddConstantN('INTERNET_SCHEME_MAILTO','LongInt').SetInt( 7);
 //CL.AddConstantN('INTERNET_SCHEME_FIRST','').SetString( INTERNET_SCHEME_FTP);
 //CL.AddConstantN('INTERNET_SCHEME_LAST','').SetString( INTERNET_SCHEME_MAILTO);
  //CL.AddTypeS('PInternetAsyncResult', '^TInternetAsyncResult // will not work');
  CL.AddTypeS('TInternetAsyncResult', 'record dwResult : DWORD; dwError : DWORD; end');
  //CL.AddTypeS('PInternetPrefetchStatus', '^TInternetPrefetchStatus // will notwork');
  CL.AddTypeS('TInternetPrefetchStatus', 'record dwStatus : DWORD; dwSize : DWORD; end');
 CL.AddConstantN('INTERNET_PREFETCH_PROGRESS','LongInt').SetInt( 0);
 CL.AddConstantN('INTERNET_PREFETCH_COMPLETE','LongInt').SetInt( 1);
 CL.AddConstantN('INTERNET_PREFETCH_ABORTED','LongInt').SetInt( 2);
  //CL.AddTypeS('PInternetProxyInfo', '^INTERNET_PROXY_INFO // will not work');
  CL.AddTypeS('INTERNET_PROXY_INFO', 'record dwAccessType : DWORD; lpszProxy : string; lpszProxyBypass : string; end');
  CL.AddTypeS('TInternetProxyInfo', 'INTERNET_PROXY_INFO');
  //CL.AddTypeS('LPINTERNET_PROXY_INFO', 'PInternetProxyInfo');
  //CL.AddTypeS('PInternetVersionInfo', '^INTERNET_VERSION_INFO // will not work');
  CL.AddTypeS('INTERNET_VERSION_INFO', 'record dwMajorVersion : DWORD; dwMinorVersion : DWORD; end');
  CL.AddTypeS('TInternetVersionInfo', 'INTERNET_VERSION_INFO');
  //CL.AddTypeS('LPINTERNET_VERSION_INFO', 'PInternetVersionInfo');
  //CL.AddTypeS('PHttpVersionInfo', '^HTTP_VERSION_INFO // will not work');
  CL.AddTypeS('HTTP_VERSION_INFO', 'record dwMajorVersion : DWORD; dwMinorVersion : DWORD; end');
  CL.AddTypeS('THttpVersionInfo', 'HTTP_VERSION_INFO');
  //CL.AddTypeS('LPHTTP_VERSION_INFO', 'PHttpVersionInfo');
  CL.AddTypeS('INTERNET_CONNECTED_INFO', 'record dwConnectedState : DWORD; dwFlags : DWORD; end');
  CL.AddTypeS('TInternetConnectedInfo', 'INTERNET_CONNECTED_INFO');
  //CL.AddTypeS('LPINTERNET_CONNECTED_INFO', 'PInternetConnectedInfo');
 CL.AddConstantN('ISO_FORCE_DISCONNECTED','LongWord').SetUInt( $00000001);
 // CL.AddTypeS('PURLComponents', '^URL_COMPONENTS // will not work');

 CL.AddTypeS('LPSTR', 'PCHar');
 CL.AddTypeS('LPCSTR', 'PCHar'); //LPCTSTR
 CL.AddTypeS('PLPSTR', 'PCHar');

  CL.AddTypeS('URL_COMPONENTS', 'record dwStructSize : DWORD; lpszScheme : LPST'
   +'R; dwSchemeLength : DWORD; nScheme : TInternetScheme; lpszHostName : LPSTR'
   +'; dwHostNameLength : DWORD; nPort : INTERNET_PORT; pad : WORD; lpszUserNam'
   +'e : LPSTR; dwUserNameLength : DWORD; lpszPassword : LPSTR; dwPasswordLengt'
   +'h : DWORD; lpszUrlPath : LPSTR; dwUrlPathLength : DWORD; lpszExtraInfo : L'
   +'PSTR; dwExtraInfoLength : DWORD; end');
  CL.AddTypeS('TURLComponents', 'URL_COMPONENTS');
  //CL.AddTypeS('LPURL_COMPONENTS', 'PURLComponents');
  //CL.AddTypeS('PInternetCertificateInfo', '^INTERNET_CERTIFICATE_INFO // will not work');
  CL.AddTypeS('INTERNET_CERTIFICATE_INFO', 'record ftExpiry : TFileTime; ftStar'
   +'t : TFileTime; lpszSubjectInfo : LPSTR; lpszIssuerInfo : LPSTR; lpszProtoc'
   +'olName : LPSTR; lpszSignatureAlgName : LPSTR; lpszEncryptionAlgName : LPST'
   +'R; dwKeySize : DWORD; end');
  CL.AddTypeS('TInternetCertificateInfo', 'INTERNET_CERTIFICATE_INFO');
  //CL.AddTypeS('LPINTERNET_CERTIFICATE_INFO', 'pInternetCertificateInfo');
  //CL.AddTypeS('PInternetBuffersA', '^INTERNET_BUFFERSA // will not work');
  //CL.AddTypeS('PInternetBuffersW', '^INTERNET_BUFFERSW // will not work');
  //CL.AddTypeS('PInternetBuffers', 'PInternetBuffersA');
  CL.AddDelphiFunction('Function InternetTimeFromSystemTime( const pst : TSystemTime; dwRFC : DWORD; lpszTime : LPSTR; cbTime : DWORD) : BOOL');
 CL.AddConstantN('INTERNET_RFC1123_FORMAT','LongInt').SetInt( 0);
 CL.AddConstantN('INTERNET_RFC1123_BUFSIZE','LongInt').SetInt( 30);
 CL.AddDelphiFunction('Function InternetCrackUrl( lpszUrl : PChar; dwUrlLength, dwFlags : DWORD; var lpUrlComponents : TURLComponents) : BOOL');
 //CL.AddDelphiFunction('Function InternetCrackUrlA( lpszUrl : PAnsiChar; dwUrlLength, dwFlags : DWORD; var lpUrlComponents : TURLComponents) : BOOL');
 //CL.AddDelphiFunction('Function InternetCrackUrlW( lpszUrl : PWideChar; dwUrlLength, dwFlags : DWORD; var lpUrlComponents : TURLComponents) : BOOL');
 CL.AddDelphiFunction('Function InternetCreateUrl( var lpUrlComponents : TURLComponents; dwFlags : DWORD; lpszUrl : PChar; var dwUrlLength : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function InternetCreateUrlA( var lpUrlComponents : TURLComponents; dwFlags : DWORD; lpszUrl : PAnsiChar; var dwUrlLength : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function InternetCreateUrlW( var lpUrlComponents : TURLComponents; dwFlags : DWORD; lpszUrl : PWideChar; var dwUrlLength : DWORD) : BOOL');
 CL.AddDelphiFunction('Function InternetCanonicalizeUrl( lpszUrl : PChar; lpszBuffer : PChar; var lpdwBufferLength : DWORD; dwFlags : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function InternetCanonicalizeUrlA( lpszUrl : PAnsiChar; lpszBuffer : PAnsiChar; var lpdwBufferLength : DWORD; dwFlags : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function InternetCanonicalizeUrlW( lpszUrl : PWideChar; lpszBuffer : PWideChar; var lpdwBufferLength : DWORD; dwFlags : DWORD) : BOOL');
 CL.AddDelphiFunction('Function InternetCombineUrl( lpszBaseUrl, lpszRelativeUrl : PChar; lpszBuffer : PChar; var lpdwBufferLength : DWORD; dwFlags : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function InternetCombineUrlA( lpszBaseUrl, lpszRelativeUrl : PAnsiChar; lpszBuffer : PAnsiChar; var lpdwBufferLength : DWORD; dwFlags : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function InternetCombineUrlW( lpszBaseUrl, lpszRelativeUrl : PWideChar; lpszBuffer : PWideChar; var lpdwBufferLength : DWORD; dwFlags : DWORD) : BOOL');
 CL.AddConstantN('ICU_ESCAPE','LongWord').SetUInt( $80000000);
 CL.AddConstantN('ICU_USERNAME','LongWord').SetUInt( $40000000);
 CL.AddConstantN('ICU_NO_ENCODE','LongWord').SetUInt( $20000000);
 CL.AddConstantN('ICU_DECODE','LongWord').SetUInt( $10000000);
 CL.AddConstantN('ICU_NO_META','LongWord').SetUInt( $08000000);
 CL.AddConstantN('ICU_ENCODE_SPACES_ONLY','LongWord').SetUInt( $04000000);
 CL.AddConstantN('ICU_BROWSER_MODE','LongWord').SetUInt( $02000000);
 CL.AddDelphiFunction('Function InternetOpen( lpszAgent : PChar; dwAccessType : DWORD; lpszProxy, lpszProxyBypass : PChar; dwFlags : DWORD) : HINTERNET');
 CL.AddDelphiFunction('Function InternetOpen2( lpszAgent : PChar; dwAccessType : DWORD; lpszProxy, lpszProxyBypass : PChar; dwFlags : DWORD) : HINTERNET');

 //CL.AddDelphiFunction('Function InternetOpenA( lpszAgent : PAnsiChar; dwAccessType : DWORD; lpszProxy, lpszProxyBypass : PAnsiChar; dwFlags : DWORD) : HINTERNET');
 //CL.AddDelphiFunction('Function InternetOpenW( lpszAgent : PWideChar; dwAccessType : DWORD; lpszProxy, lpszProxyBypass : PWideChar; dwFlags : DWORD) : HINTERNET');
 CL.AddConstantN('INTERNET_OPEN_TYPE_PRECONFIG','LongInt').SetInt( 0);
 CL.AddConstantN('INTERNET_OPEN_TYPE_DIRECT','LongInt').SetInt( 1);
 CL.AddConstantN('INTERNET_OPEN_TYPE_PROXY','LongInt').SetInt( 3);
 CL.AddConstantN('INTERNET_OPEN_TYPE_PRECONFIG_WITH_NO_AUTOPROXY','LongInt').SetInt( 4);
 //CL.AddConstantN('PRE_CONFIG_INTERNET_ACCESS','').SetString( INTERNET_OPEN_TYPE_PRECONFIG);
 //CL.AddConstantN('LOCAL_INTERNET_ACCESS','').SetString( INTERNET_OPEN_TYPE_DIRECT);
 CL.AddConstantN('GATEWAY_INTERNET_ACCESS','LongInt').SetInt( 2);
 //CL.AddConstantN('CERN_PROXY_INTERNET_ACCESS','').SetString( INTERNET_OPEN_TYPE_PROXY);
 CL.AddDelphiFunction('Function InternetCloseHandle( hInet : HINTERNET) : BOOL');
 CL.AddDelphiFunction('Function InternetConnect( hInet : HINTERNET; lpszServerName : PChar; nServerPort : INTERNET_PORT; lpszUsername : PChar; lpszPassword : PChar; dwService : DWORD; dwFlags : DWORD; dwContext : DWORD) : HINTERNET');
 //CL.AddDelphiFunction('Function InternetConnectA( hInet : HINTERNET; lpszServerName : PAnsiChar; nServerPort : INTERNET_PORT; lpszUsername : PAnsiChar; lpszPassword : PAnsiChar; dwService : DWORD; dwFlags : DWORD; dwContext : DWORD) : HINTERNET');
 //CL.AddDelphiFunction('Function InternetConnectW( hInet : HINTERNET; lpszServerName : PWideChar; nServerPort : INTERNET_PORT; lpszUsername : PWideChar; lpszPassword : PWideChar; dwService : DWORD; dwFlags : DWORD; dwContext : DWORD) : HINTERNET');
 CL.AddConstantN('INTERNET_SERVICE_URL','LongInt').SetInt( 0);
 CL.AddConstantN('INTERNET_SERVICE_FTP','LongInt').SetInt( 1);
 CL.AddConstantN('INTERNET_SERVICE_GOPHER','LongInt').SetInt( 2);
 CL.AddConstantN('INTERNET_SERVICE_HTTP','LongInt').SetInt( 3);
 CL.AddDelphiFunction('Function InternetOpenUrl( hInet : HINTERNET; lpszUrl : PChar; lpszHeaders : PChar; dwHeadersLength : DWORD; dwFlags : DWORD; dwContext : DWORD) : HINTERNET');
 CL.AddDelphiFunction('Function InternetOpenUrl2( hInet : HINTERNET; lpszUrl : PChar; lpszHeaders : TObject; dwHeadersLength : DWORD; dwFlags : DWORD; dwContext : DWORD) : HINTERNET');

 //CL.AddDelphiFunction('Function InternetOpenUrlA( hInet : HINTERNET; lpszUrl : PAnsiChar; lpszHeaders : PAnsiChar; dwHeadersLength : DWORD; dwFlags : DWORD; dwContext : DWORD) : HINTERNET');
 //CL.AddDelphiFunction('Function InternetOpenUrlW( hInet : HINTERNET; lpszUrl : PWideChar; lpszHeaders : PWideChar; dwHeadersLength : DWORD; dwFlags : DWORD; dwContext : DWORD) : HINTERNET');
 //CL.AddDelphiFunction('Function InternetReadFile( hFile : HINTERNET; lpBuffer : Pointer; dwNumberOfBytesToRead : DWORD; var lpdwNumberOfBytesRead : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function InternetReadFileEx( hFile : HINTERNET; lpBuffersOut : Pointer; dwFlags : DWORD; dwContext : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function InternetReadFileExA( hFile : HINTERNET; lpBuffersOut : Pointer; dwFlags : DWORD; dwContext : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function InternetReadFileExW( hFile : HINTERNET; lpBuffersOut : Pointer; dwFlags : DWORD; dwContext : DWORD) : BOOL');
 //CL.AddConstantN('IRF_ASYNC','').SetString( WININET_API_FLAG_ASYNC);
 //CL.AddConstantN('IRF_SYNC','').SetString( WININET_API_FLAG_SYNC);
 //CL.AddConstantN('IRF_USE_CONTEXT','').SetString( WININET_API_FLAG_USE_CONTEXT);
 CL.AddConstantN('IRF_NO_WAIT','LongWord').SetUInt( $00000008);
 //CL.AddDelphiFunction('Function InternetSetFilePointer( hFile : HINTERNET; lDistanceToMove : Longint; pReserved : Pointer; dwMoveMethod, dwContext : DWORD) : DWORD');
 //CL.AddDelphiFunction('Function InternetWriteFile( hFile : HINTERNET; lpBuffer : Pointer; dwNumberOfBytesToWrite : DWORD; var lpdwNumberOfBytesWritten : DWORD) : BOOL');
 CL.AddDelphiFunction('Function InternetQueryDataAvailable( hFile : HINTERNET; var lpdwNumberOfBytesAvailable : DWORD; dwFlags, dwContext : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function InternetFindNextFile( hFind : HINTERNET; lpvFindData : Pointer) : BOOL');
 //CL.AddDelphiFunction('Function InternetFindNextFileA( hFind : HINTERNET; lpvFindData : Pointer) : BOOL');
 //CL.AddDelphiFunction('Function InternetFindNextFileW( hFind : HINTERNET; lpvFindData : Pointer) : BOOL');
 {CL.AddDelphiFunction('Function InternetQueryOption( hInet : HINTERNET; dwOption : DWORD; lpBuffer : Pointer; var lpdwBufferLength : DWORD) : BOOL');
 CL.AddDelphiFunction('Function InternetQueryOptionA( hInet : HINTERNET; dwOption : DWORD; lpBuffer : Pointer; var lpdwBufferLength : DWORD) : BOOL');
 CL.AddDelphiFunction('Function InternetQueryOptionW( hInet : HINTERNET; dwOption : DWORD; lpBuffer : Pointer; var lpdwBufferLength : DWORD) : BOOL');
 CL.AddDelphiFunction('Function InternetSetOption( hInet : HINTERNET; dwOption : DWORD; lpBuffer : Pointer; dwBufferLength : DWORD) : BOOL');
 CL.AddDelphiFunction('Function InternetSetOptionA( hInet : HINTERNET; dwOption : DWORD; lpBuffer : Pointer; dwBufferLength : DWORD) : BOOL');
 CL.AddDelphiFunction('Function InternetSetOptionW( hInet : HINTERNET; dwOption : DWORD; lpBuffer : Pointer; dwBufferLength : DWORD) : BOOL');
 CL.AddDelphiFunction('Function InternetSetOptionEx( hInet : HINTERNET; dwOption : DWORD; lpBuffer : Pointer; dwBufferLength, dwFlags : DWORD) : BOOL');
 CL.AddDelphiFunction('Function InternetSetOptionExA( hInet : HINTERNET; dwOption : DWORD; lpBuffer : Pointer; dwBufferLength, dwFlags : DWORD) : BOOL');
 CL.AddDelphiFunction('Function InternetSetOptionExW( hInet : HINTERNET; dwOption : DWORD; lpBuffer : Pointer; dwBufferLength, dwFlags : DWORD) : BOOL');
 CL.AddDelphiFunction('Function InternetLockRequestFile( hInternet : HINTERNET; lphLockRequestInfo : PHandle) : BOOL');}
 CL.AddDelphiFunction('Function InternetUnlockRequestFile( hLockRequestInfo : THANDLE) : BOOL');
 CL.AddConstantN('ISO_GLOBAL','LongWord').SetUInt( $00000001);
 CL.AddConstantN('ISO_REGISTRY','LongWord').SetUInt( $00000002);
 CL.AddConstantN('INTERNET_OPTION_CALLBACK','LongInt').SetInt( 1);
 CL.AddConstantN('INTERNET_OPTION_CONNECT_TIMEOUT','LongInt').SetInt( 2);
 CL.AddConstantN('INTERNET_OPTION_CONNECT_RETRIES','LongInt').SetInt( 3);
 CL.AddConstantN('INTERNET_OPTION_CONNECT_BACKOFF','LongInt').SetInt( 4);
 CL.AddConstantN('INTERNET_OPTION_SEND_TIMEOUT','LongInt').SetInt( 5);
 //CL.AddConstantN('INTERNET_OPTION_CONTROL_SEND_TIMEOUT','').SetString( INTERNET_OPTION_SEND_TIMEOUT);
 CL.AddConstantN('INTERNET_OPTION_RECEIVE_TIMEOUT','LongInt').SetInt( 6);
 //CL.AddConstantN('INTERNET_OPTION_CONTROL_RECEIVE_TIMEOUT','').SetString( INTERNET_OPTION_RECEIVE_TIMEOUT);
 CL.AddConstantN('INTERNET_OPTION_DATA_SEND_TIMEOUT','LongInt').SetInt( 7);
 CL.AddConstantN('INTERNET_OPTION_DATA_RECEIVE_TIMEOUT','LongInt').SetInt( 8);
 CL.AddConstantN('INTERNET_OPTION_HANDLE_TYPE','LongInt').SetInt( 9);
 CL.AddConstantN('INTERNET_OPTION_READ_BUFFER_SIZE','LongInt').SetInt( 12);
 CL.AddConstantN('INTERNET_OPTION_WRITE_BUFFER_SIZE','LongInt').SetInt( 13);
 CL.AddConstantN('INTERNET_OPTION_ASYNC_ID','LongInt').SetInt( 15);
 CL.AddConstantN('INTERNET_OPTION_ASYNC_PRIORITY','LongInt').SetInt( 16);
 CL.AddConstantN('INTERNET_OPTION_PARENT_HANDLE','LongInt').SetInt( 21);
 CL.AddConstantN('INTERNET_OPTION_KEEP_CONNECTION','LongInt').SetInt( 22);
 CL.AddConstantN('INTERNET_OPTION_REQUEST_FLAGS','LongInt').SetInt( 23);
 CL.AddConstantN('INTERNET_OPTION_EXTENDED_ERROR','LongInt').SetInt( 24);
 CL.AddConstantN('INTERNET_OPTION_OFFLINE_MODE','LongInt').SetInt( 26);
 CL.AddConstantN('INTERNET_OPTION_CACHE_STREAM_HANDLE','LongInt').SetInt( 27);
 CL.AddConstantN('INTERNET_OPTION_USERNAME','LongInt').SetInt( 28);
 CL.AddConstantN('INTERNET_OPTION_PASSWORD','LongInt').SetInt( 29);
 CL.AddConstantN('INTERNET_OPTION_ASYNC','LongInt').SetInt( 30);
 CL.AddConstantN('INTERNET_OPTION_SECURITY_FLAGS','LongInt').SetInt( 31);
 CL.AddConstantN('INTERNET_OPTION_SECURITY_CERTIFICATE_STRUCT','LongInt').SetInt( 32);
 CL.AddConstantN('INTERNET_OPTION_DATAFILE_NAME','LongInt').SetInt( 33);
 CL.AddConstantN('INTERNET_OPTION_URL','LongInt').SetInt( 34);
 CL.AddConstantN('INTERNET_OPTION_SECURITY_CERTIFICATE','LongInt').SetInt( 35);
 CL.AddConstantN('INTERNET_OPTION_SECURITY_KEY_BITNESS','LongInt').SetInt( 36);
 CL.AddConstantN('INTERNET_OPTION_REFRESH','LongInt').SetInt( 37);
 CL.AddConstantN('INTERNET_OPTION_PROXY','LongInt').SetInt( 38);
 CL.AddConstantN('INTERNET_OPTION_SETTINGS_CHANGED','LongInt').SetInt( 39);
 CL.AddConstantN('INTERNET_OPTION_VERSION','LongInt').SetInt( 40);
 CL.AddConstantN('INTERNET_OPTION_USER_AGENT','LongInt').SetInt( 41);
 CL.AddConstantN('INTERNET_OPTION_END_BROWSER_SESSION','LongInt').SetInt( 42);
 CL.AddConstantN('INTERNET_OPTION_PROXY_USERNAME','LongInt').SetInt( 43);
 CL.AddConstantN('INTERNET_OPTION_PROXY_PASSWORD','LongInt').SetInt( 44);
 CL.AddConstantN('INTERNET_OPTION_CONTEXT_VALUE','LongInt').SetInt( 45);
 CL.AddConstantN('INTERNET_OPTION_CONNECT_LIMIT','LongInt').SetInt( 46);
 CL.AddConstantN('INTERNET_OPTION_SECURITY_SELECT_CLIENT_CERT','LongInt').SetInt( 47);
 CL.AddConstantN('INTERNET_OPTION_POLICY','LongInt').SetInt( 48);
 CL.AddConstantN('INTERNET_OPTION_DISCONNECTED_TIMEOUT','LongInt').SetInt( 49);
 CL.AddConstantN('INTERNET_OPTION_CONNECTED_STATE','LongInt').SetInt( 50);
 CL.AddConstantN('INTERNET_OPTION_IDLE_STATE','LongInt').SetInt( 51);
 CL.AddConstantN('INTERNET_OPTION_OFFLINE_SEMANTICS','LongInt').SetInt( 52);
 CL.AddConstantN('INTERNET_OPTION_SECONDARY_CACHE_KEY','LongInt').SetInt( 53);
 CL.AddConstantN('INTERNET_OPTION_CALLBACK_FILTER','LongInt').SetInt( 54);
 CL.AddConstantN('INTERNET_OPTION_CONNECT_TIME','LongInt').SetInt( 55);
 CL.AddConstantN('INTERNET_OPTION_SEND_THROUGHPUT','LongInt').SetInt( 56);
 CL.AddConstantN('INTERNET_OPTION_RECEIVE_THROUGHPUT','LongInt').SetInt( 57);
 CL.AddConstantN('INTERNET_OPTION_REQUEST_PRIORITY','LongInt').SetInt( 58);
 CL.AddConstantN('INTERNET_OPTION_HTTP_VERSION','LongInt').SetInt( 59);
 CL.AddConstantN('INTERNET_OPTION_RESET_URLCACHE_SESSION','LongInt').SetInt( 60);
 CL.AddConstantN('INTERNET_OPTION_ERROR_MASK','LongInt').SetInt( 62);
 //CL.AddConstantN('INTERNET_FIRST_OPTION','').SetString( INTERNET_OPTION_CALLBACK);
 //CL.AddConstantN('INTERNET_LAST_OPTION','').SetString( INTERNET_OPTION_PROXY);
 CL.AddConstantN('INTERNET_PRIORITY_FOREGROUND','LongInt').SetInt( 1000);
 CL.AddConstantN('INTERNET_HANDLE_TYPE_INTERNET','LongInt').SetInt( 1);
 CL.AddConstantN('INTERNET_HANDLE_TYPE_CONNECT_FTP','LongInt').SetInt( 2);
 CL.AddConstantN('INTERNET_HANDLE_TYPE_CONNECT_GOPHER','LongInt').SetInt( 3);
 CL.AddConstantN('INTERNET_HANDLE_TYPE_CONNECT_HTTP','LongInt').SetInt( 4);
 CL.AddConstantN('INTERNET_HANDLE_TYPE_FTP_FIND','LongInt').SetInt( 5);
 CL.AddConstantN('INTERNET_HANDLE_TYPE_FTP_FIND_HTML','LongInt').SetInt( 6);
 CL.AddConstantN('INTERNET_HANDLE_TYPE_FTP_FILE','LongInt').SetInt( 7);
 CL.AddConstantN('INTERNET_HANDLE_TYPE_FTP_FILE_HTML','LongInt').SetInt( 8);
 CL.AddConstantN('INTERNET_HANDLE_TYPE_GOPHER_FIND','LongInt').SetInt( 9);
 CL.AddConstantN('INTERNET_HANDLE_TYPE_GOPHER_FIND_HTML','LongInt').SetInt( 10);
 CL.AddConstantN('INTERNET_HANDLE_TYPE_GOPHER_FILE','LongInt').SetInt( 11);
 CL.AddConstantN('INTERNET_HANDLE_TYPE_GOPHER_FILE_HTML','LongInt').SetInt( 12);
 CL.AddConstantN('INTERNET_HANDLE_TYPE_HTTP_REQUEST','LongInt').SetInt( 13);
 CL.AddConstantN('SECURITY_FLAG_SECURE','LongWord').SetUInt( $00000001);
 CL.AddConstantN('SECURITY_FLAG_SSL','LongWord').SetUInt( $00000002);
 CL.AddConstantN('SECURITY_FLAG_SSL3','LongWord').SetUInt( $00000004);
 CL.AddConstantN('SECURITY_FLAG_PCT','LongWord').SetUInt( $00000008);
 CL.AddConstantN('SECURITY_FLAG_PCT4','LongWord').SetUInt( $00000010);
 CL.AddConstantN('SECURITY_FLAG_IETFSSL4','LongWord').SetUInt( $00000020);
 CL.AddConstantN('SECURITY_FLAG_STRENGTH_WEAK','LongWord').SetUInt( $10000000);
 CL.AddConstantN('SECURITY_FLAG_STRENGTH_MEDIUM','LongWord').SetUInt( $40000000);
 CL.AddConstantN('SECURITY_FLAG_STRENGTH_STRONG','LongWord').SetUInt( $20000000);
 //CL.AddConstantN('SECURITY_FLAG_40BIT','').SetString( SECURITY_FLAG_STRENGTH_WEAK);
 //CL.AddConstantN('SECURITY_FLAG_128BIT','').SetString( SECURITY_FLAG_STRENGTH_STRONG);
 //CL.AddConstantN('SECURITY_FLAG_56BIT','').SetString( SECURITY_FLAG_STRENGTH_MEDIUM);
 CL.AddConstantN('SECURITY_FLAG_UNKNOWNBIT','LongWord').SetUInt( $80000000);
 //CL.AddConstantN('SECURITY_FLAG_NORMALBITNESS','').SetString( SECURITY_FLAG_40BIT);
 CL.AddConstantN('SECURITY_FLAG_IGNORE_REVOCATION','LongWord').SetUInt( $00000080);
 CL.AddConstantN('SECURITY_FLAG_IGNORE_UNKNOWN_CA','LongWord').SetUInt( $00000100);
 CL.AddConstantN('SECURITY_FLAG_IGNORE_WRONG_USAGE','LongWord').SetUInt( $00000200);
 //CL.AddConstantN('SECURITY_FLAG_IGNORE_CERT_CN_INVALID','').SetString( INTERNET_FLAG_IGNORE_CERT_CN_INVALID);
 //CL.AddConstantN('SECURITY_FLAG_IGNORE_CERT_DATE_INVALID','').SetString( INTERNET_FLAG_IGNORE_CERT_DATE_INVALID);
 //CL.AddConstantN('SECURITY_FLAG_IGNORE_REDIRECT_TO_HTTPS','').SetString( INTERNET_FLAG_IGNORE_REDIRECT_TO_HTTPS);
 //CL.AddConstantN('SECURITY_FLAG_IGNORE_REDIRECT_TO_HTTP','').SetString( INTERNET_FLAG_IGNORE_REDIRECT_TO_HTTP);
 //CL.AddDelphiFunction('Function InternetGetLastResponseInfo( var lpdwError : DWORD; lpszBuffer : PChar; var lpdwBufferLength : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function InternetGetLastResponseInfoA( var lpdwError : DWORD; lpszBuffer : PAnsiChar; var lpdwBufferLength : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function InternetGetLastResponseInfoW( var lpdwError : DWORD; lpszBuffer : PWideChar; var lpdwBufferLength : DWORD) : BOOL');
  CL.AddTypeS('INTERNET_STATUS_CALLBACK', 'TObject');
  CL.AddTypeS('TFNInternetStatusCallback', 'INTERNET_STATUS_CALLBACK');
  //CL.AddTypeS('PFNInternetStatusCallback', '^TFNInternetStatusCallback // will not work');
  //CL.AddTypeS('LPINTERNET_STATUS_CALLBACK', 'PFNInternetStatusCallback');
 //CL.AddDelphiFunction('Function InternetSetStatusCallback( hInet : HINTERNET; lpfnInternetCallback : PFNInternetStatusCallback) : PFNInternetStatusCallback');
 CL.AddConstantN('INTERNET_STATUS_RESOLVING_NAME','LongInt').SetInt( 10);
 CL.AddConstantN('INTERNET_STATUS_NAME_RESOLVED','LongInt').SetInt( 11);
 CL.AddConstantN('INTERNET_STATUS_CONNECTING_TO_SERVER','LongInt').SetInt( 20);
 CL.AddConstantN('INTERNET_STATUS_CONNECTED_TO_SERVER','LongInt').SetInt( 21);
 CL.AddConstantN('INTERNET_STATUS_SENDING_REQUEST','LongInt').SetInt( 30);
 CL.AddConstantN('INTERNET_STATUS_REQUEST_SENT','LongInt').SetInt( 31);
 CL.AddConstantN('INTERNET_STATUS_RECEIVING_RESPONSE','LongInt').SetInt( 40);
 CL.AddConstantN('INTERNET_STATUS_RESPONSE_RECEIVED','LongInt').SetInt( 41);
 CL.AddConstantN('INTERNET_STATUS_CTL_RESPONSE_RECEIVED','LongInt').SetInt( 42);
 CL.AddConstantN('INTERNET_STATUS_PREFETCH','LongInt').SetInt( 43);
 CL.AddConstantN('INTERNET_STATUS_CLOSING_CONNECTION','LongInt').SetInt( 50);
 CL.AddConstantN('INTERNET_STATUS_CONNECTION_CLOSED','LongInt').SetInt( 51);
 CL.AddConstantN('INTERNET_STATUS_HANDLE_CREATED','LongInt').SetInt( 60);
 CL.AddConstantN('INTERNET_STATUS_HANDLE_CLOSING','LongInt').SetInt( 70);
 CL.AddConstantN('INTERNET_STATUS_REQUEST_COMPLETE','LongInt').SetInt( 100);
 CL.AddConstantN('INTERNET_STATUS_REDIRECT','LongInt').SetInt( 110);
 CL.AddConstantN('INTERNET_STATUS_INTERMEDIATE_RESPONSE','LongInt').SetInt( 120);
 CL.AddConstantN('INTERNET_STATUS_STATE_CHANGE','LongInt').SetInt( 200);
 CL.AddConstantN('INTERNET_STATE_CONNECTED','LongWord').SetUInt( $00000001);
 CL.AddConstantN('INTERNET_STATE_DISCONNECTED','LongWord').SetUInt( $00000002);
 CL.AddConstantN('INTERNET_STATE_DISCONNECTED_BY_USER','LongWord').SetUInt( $00000010);
 CL.AddConstantN('INTERNET_STATE_IDLE','LongWord').SetUInt( $00000100);
 CL.AddConstantN('INTERNET_STATE_BUSY','LongWord').SetUInt( $00000200);
 CL.AddConstantN('INTERNET_INVALID_STATUS_CALLBACK','LongInt').SetInt( ( - 1 ));
 CL.AddDelphiFunction('Function FtpFindFirstFile( hConnect : HINTERNET; lpszSearchFile : PChar; var lpFindFileData : TWin32FindData; dwFlags : DWORD; dwContext : DWORD) : HINTERNET');
 //CL.AddDelphiFunction('Function FtpFindFirstFileA( hConnect : HINTERNET; lpszSearchFile : PAnsiChar; var lpFindFileData : TWin32FindDataA; dwFlags : DWORD; dwContext : DWORD) : HINTERNET');
 //CL.AddDelphiFunction('Function FtpFindFirstFileW( hConnect : HINTERNET; lpszSearchFile : PWideChar; var lpFindFileData : TWin32FindDataW; dwFlags : DWORD; dwContext : DWORD) : HINTERNET');
 CL.AddDelphiFunction('Function WFtpGetFile( hConnect : HINTERNET; lpszRemoteFile : PChar; lpszNewFile : PChar; fFailIfExists : BOOL; dwFlagsAndAttributes : DWORD; dwFlags : DWORD; dwContext : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function FtpGetFileA( hConnect : HINTERNET; lpszRemoteFile : PAnsiChar; lpszNewFile : PAnsiChar; fFailIfExists : BOOL; dwFlagsAndAttributes : DWORD; dwFlags : DWORD; dwContext : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function FtpGetFileW( hConnect : HINTERNET; lpszRemoteFile : PWideChar; lpszNewFile : PWideChar; fFailIfExists : BOOL; dwFlagsAndAttributes : DWORD; dwFlags : DWORD; dwContext : DWORD) : BOOL');
 CL.AddDelphiFunction('Function WFtpPutFile( hConnect : HINTERNET; lpszLocalFile : PChar; lpszNewRemoteFile : PChar; dwFlags : DWORD; dwContext : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function FtpPutFileA( hConnect : HINTERNET; lpszLocalFile : PAnsiChar; lpszNewRemoteFile : PAnsiChar; dwFlags : DWORD; dwContext : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function FtpPutFileW( hConnect : HINTERNET; lpszLocalFile : PWideChar; lpszNewRemoteFile : PWideChar; dwFlags : DWORD; dwContext : DWORD) : BOOL');
 CL.AddDelphiFunction('Function FtpDeleteFile( hConnect : HINTERNET; lpszFileName : PChar) : BOOL');
 //CL.AddDelphiFunction('Function FtpDeleteFileA( hConnect : HINTERNET; lpszFileName : PAnsiChar) : BOOL');
 //CL.AddDelphiFunction('Function FtpDeleteFileW( hConnect : HINTERNET; lpszFileName : PWideChar) : BOOL');
 CL.AddDelphiFunction('Function FtpRenameFile( hConnect : HINTERNET; lpszExisting : PChar; lpszNew : PChar) : BOOL');
 //CL.AddDelphiFunction('Function FtpRenameFileA( hConnect : HINTERNET; lpszExisting : PAnsiChar; lpszNew : PAnsiChar) : BOOL');
 //CL.AddDelphiFunction('Function FtpRenameFileW( hConnect : HINTERNET; lpszExisting : PWideChar; lpszNew : PWideChar) : BOOL');
 CL.AddDelphiFunction('Function FtpOpenFile( hConnect : HINTERNET; lpszFileName : PChar; dwAccess : DWORD; dwFlags : DWORD; dwContext : DWORD) : HINTERNET');
 //CL.AddDelphiFunction('Function FtpOpenFileA( hConnect : HINTERNET; lpszFileName : PAnsiChar; dwAccess : DWORD; dwFlags : DWORD; dwContext : DWORD) : HINTERNET');
 //CL.AddDelphiFunction('Function FtpOpenFileW( hConnect : HINTERNET; lpszFileName : PWideChar; dwAccess : DWORD; dwFlags : DWORD; dwContext : DWORD) : HINTERNET');
 CL.AddDelphiFunction('Function FtpCreateDirectory( hConnect : HINTERNET; lpszDirectory : PChar) : BOOL');
 //CL.AddDelphiFunction('Function FtpCreateDirectoryA( hConnect : HINTERNET; lpszDirectory : PAnsiChar) : BOOL');
 //CL.AddDelphiFunction('Function FtpCreateDirectoryW( hConnect : HINTERNET; lpszDirectory : PWideChar) : BOOL');
 CL.AddDelphiFunction('Function FtpRemoveDirectory( hConnect : HINTERNET; lpszDirectory : PChar) : BOOL');
 //CL.AddDelphiFunction('Function FtpRemoveDirectoryA( hConnect : HINTERNET; lpszDirectory : PAnsiChar) : BOOL');
 //CL.AddDelphiFunction('Function FtpRemoveDirectoryW( hConnect : HINTERNET; lpszDirectory : PWideChar) : BOOL');
 CL.AddDelphiFunction('Function FtpSetCurrentDirectory( hConnect : HINTERNET; lpszDirectory : PChar) : BOOL');
 //CL.AddDelphiFunction('Function FtpSetCurrentDirectoryA( hConnect : HINTERNET; lpszDirectory : PAnsiChar) : BOOL');
 //CL.AddDelphiFunction('Function FtpSetCurrentDirectoryW( hConnect : HINTERNET; lpszDirectory : PWideChar) : BOOL');
 CL.AddDelphiFunction('Function FtpGetCurrentDirectory( hConnect : HINTERNET; lpszCurrentDirectory : PChar; var lpdwCurrentDirectory : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function FtpGetCurrentDirectoryA( hConnect : HINTERNET; lpszCurrentDirectory : PAnsiChar; var lpdwCurrentDirectory : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function FtpGetCurrentDirectoryW( hConnect : HINTERNET; lpszCurrentDirectory : PWideChar; var lpdwCurrentDirectory : DWORD) : BOOL');
 CL.AddDelphiFunction('Function FtpCommand( hConnect : HINTERNET; fExpectResponse : BOOL; dwFlags : DWORD; lpszCommand : PChar; dwContext : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function FtpCommandA( hConnect : HINTERNET; fExpectResponse : BOOL; dwFlags : DWORD; lpszCommand : PAnsiChar; dwContext : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function FtpCommandW( hConnect : HINTERNET; fExpectResponse : BOOL; dwFlags : DWORD; lpszCommand : PWideChar; dwContext : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function FtpGetFileSize( hFile : HINTERNET; lpdwFileSizeHigh : LPDWORD) : DWORD');
 CL.AddConstantN('MAX_GOPHER_DISPLAY_TEXT','LongInt').SetInt( 128);
 CL.AddConstantN('MAX_GOPHER_SELECTOR_TEXT','LongInt').SetInt( 256);
 //CL.AddConstantN('MAX_GOPHER_HOST_NAME','').SetString( INTERNET_MAX_HOST_NAME_LENGTH);
  //CL.AddTypeS('PGopherFindDataA', '^GOPHER_FIND_DATAA // will not work');
  //CL.AddTypeS('PGopherFindDataW', '^GOPHER_FIND_DATAW // will not work');
  //CL.AddTypeS('PGopherFindData', 'PGopherFindDataA');
 CL.AddConstantN('GOPHER_TYPE_TEXT_FILE','LongWord').SetUInt( $00000001);
 CL.AddConstantN('GOPHER_TYPE_DIRECTORY','LongWord').SetUInt( $00000002);
 CL.AddConstantN('GOPHER_TYPE_CSO','LongWord').SetUInt( $00000004);
 CL.AddConstantN('GOPHER_TYPE_ERROR','LongWord').SetUInt( $00000008);
 CL.AddConstantN('GOPHER_TYPE_MAC_BINHEX','LongWord').SetUInt( $00000010);
 CL.AddConstantN('GOPHER_TYPE_DOS_ARCHIVE','LongWord').SetUInt( $00000020);
 CL.AddConstantN('GOPHER_TYPE_UNIX_UUENCODED','LongWord').SetUInt( $00000040);
 CL.AddConstantN('GOPHER_TYPE_INDEX_SERVER','LongWord').SetUInt( $00000080);
 CL.AddConstantN('GOPHER_TYPE_TELNET','LongWord').SetUInt( $00000100);
 CL.AddConstantN('GOPHER_TYPE_BINARY','LongWord').SetUInt( $00000200);
 CL.AddConstantN('GOPHER_TYPE_REDUNDANT','LongWord').SetUInt( $00000400);
 CL.AddConstantN('GOPHER_TYPE_TN3270','LongWord').SetUInt( $00000800);
 CL.AddConstantN('GOPHER_TYPE_GIF','LongWord').SetUInt( $00001000);
 CL.AddConstantN('GOPHER_TYPE_IMAGE','LongWord').SetUInt( $00002000);
 CL.AddConstantN('GOPHER_TYPE_BITMAP','LongWord').SetUInt( $00004000);
 CL.AddConstantN('GOPHER_TYPE_MOVIE','LongWord').SetUInt( $00008000);
 CL.AddConstantN('GOPHER_TYPE_SOUND','LongWord').SetUInt( $00010000);
 CL.AddConstantN('GOPHER_TYPE_HTML','LongWord').SetUInt( $00020000);
 CL.AddConstantN('GOPHER_TYPE_PDF','LongWord').SetUInt( $00040000);
 CL.AddConstantN('GOPHER_TYPE_CALENDAR','LongWord').SetUInt( $00080000);
 CL.AddConstantN('GOPHER_TYPE_INLINE','LongWord').SetUInt( $00100000);
 CL.AddConstantN('GOPHER_TYPE_UNKNOWN','LongWord').SetUInt( $20000000);
 CL.AddConstantN('GOPHER_TYPE_ASK','LongWord').SetUInt( $40000000);
 CL.AddConstantN('GOPHER_TYPE_GOPHER_PLUS','LongWord').SetUInt( $80000000);
 CL.AddDelphiFunction('Function IS_GOPHER_FILE( GopherType : DWORD) : BOOL');
 CL.AddDelphiFunction('Function IS_GOPHER_DIRECTORY( GopherType : DWORD) : BOOL');
 CL.AddDelphiFunction('Function IS_GOPHER_PHONE_SERVER( GopherType : DWORD) : BOOL');
 CL.AddDelphiFunction('Function IS_GOPHER_ERROR( GopherType : DWORD) : BOOL');
 CL.AddDelphiFunction('Function IS_GOPHER_INDEX_SERVER( GopherType : DWORD) : BOOL');
 CL.AddDelphiFunction('Function IS_GOPHER_TELNET_SESSION( GopherType : DWORD) : BOOL');
 CL.AddDelphiFunction('Function IS_GOPHER_BACKUP_SERVER( GopherType : DWORD) : BOOL');
 CL.AddDelphiFunction('Function IS_GOPHER_TN3270_SESSION( GopherType : DWORD) : BOOL');
 CL.AddDelphiFunction('Function IS_GOPHER_ASK( GopherType : DWORD) : BOOL');
 CL.AddDelphiFunction('Function IS_GOPHER_PLUS( GopherType : DWORD) : BOOL');
 CL.AddDelphiFunction('Function IS_GOPHER_TYPE_KNOWN( GopherType : DWORD) : BOOL');
  CL.AddTypeS('GOPHER_ADMIN_ATTRIBUTE_TYPE', 'record Comment : LPCSTR; EmailAddress : LPCSTR; end');
  CL.AddTypeS('TGopherAdminAttributeType', 'GOPHER_ADMIN_ATTRIBUTE_TYPE');
 // CL.AddTypeS('LPGOPHER_ADMIN_ATTRIBUTE_TYPE', 'PGopherAdminAttributeType');
  CL.AddTypeS('GOPHER_MOD_DATE_ATTRIBUTE_TYPE', 'record DateAndTime : TFileTime; end');
  CL.AddTypeS('TGopherModDateAttributeType', 'GOPHER_MOD_DATE_ATTRIBUTE_TYPE');
  CL.AddTypeS('GOPHER_TTL_ATTRIBUTE_TYPE', 'record Ttl : DWORD; end');
  CL.AddTypeS('TGopherTtlAttributeType', 'GOPHER_TTL_ATTRIBUTE_TYPE');
  //CL.AddTypeS('LPGOPHER_TTL_ATTRIBUTE_TYPE', 'PGopherTtlAttributeType');
  CL.AddTypeS('GOPHER_SCORE_ATTRIBUTE_TYPE', 'record Score : Integer; end');
  CL.AddTypeS('TGopherScoreAttributeType', 'GOPHER_SCORE_ATTRIBUTE_TYPE');
  //CL.AddTypeS('LPGOPHER_SCORE_ATTRIBUTE_TYPE', 'PGopherScoreAttributeType');
  CL.AddTypeS('GOPHER_SCORE_RANGE_ATTRIBUTE_TYPE', 'record LowerBound : Integer; UpperBound : Integer; end');
  CL.AddTypeS('TGopherScoreRangeAttributeType', 'GOPHER_SCORE_RANGE_ATTRIBUTE_TYPE');
  CL.AddTypeS('GOPHER_SITE_ATTRIBUTE_TYPE', 'record Site : LPCSTR; end');
  CL.AddTypeS('TGopherSiteAttributeType', 'GOPHER_SITE_ATTRIBUTE_TYPE');
  //CL.AddTypeS('LPGOPHER_SITE_ATTRIBUTE_TYPE', 'PGopherSiteAttributeType');
  CL.AddTypeS('GOPHER_ORGANIZATION_ATTRIBUTE_TYPE', 'record Organization : LPCSTR; end');
  CL.AddTypeS('TGopherOrganizationAttributeType', 'GOPHER_ORGANIZATION_ATTRIBUTE_TYPE');
  CL.AddTypeS('GOPHER_LOCATION_ATTRIBUTE_TYPE', 'record Location : LPCSTR; end');
  CL.AddTypeS('TGopherLocationAttributeType', 'GOPHER_LOCATION_ATTRIBUTE_TYPE');
 // CL.AddTypeS('LPGOPHER_LOCATION_ATTRIBUTE_TYPE', 'PGopherLocationAttributeType');
  CL.AddTypeS('GOPHER_GEOGRAPHICAL_LOCATION_ATTRIBUTE_TYPE', 'record DegreesNor'
   +'th : Integer; MinutesNorth : Integer; SecondsNorth : Integer; DegreesEast '
   +': Integer; MinutesEast : Integer; SecondsEast : Integer; end');
  CL.AddTypeS('TGopherGeographicalLocationAttributeType', 'GOPHER_GEOGRAPHICAL_LOCATION_ATTRIBUTE_TYPE');
  //CL.AddTypeS('LPGOPHER_GEOGRAPHICAL_LOCATION_ATTRIBUTE_TYPE', 'PGopherGeographicalLocationAttributeType');
  CL.AddTypeS('GOPHER_TIMEZONE_ATTRIBUTE_TYPE', 'record Zone : Integer; end');
  CL.AddTypeS('TGopherTimezoneAttributeType', 'GOPHER_TIMEZONE_ATTRIBUTE_TYPE');
  //CL.AddTypeS('LPGOPHER_TIMEZONE_ATTRIBUTE_TYPE', 'PGopherTimezoneAttributeType');
  CL.AddTypeS('GOPHER_PROVIDER_ATTRIBUTE_TYPE', 'record Provider : LPCSTR; end');
  CL.AddTypeS('TGopherProviderAttributeType', 'GOPHER_PROVIDER_ATTRIBUTE_TYPE');
  //CL.AddTypeS('LPGOPHER_PROVIDER_ATTRIBUTE_TYPE', 'PGopherProviderAttributeType');
  CL.AddTypeS('GOPHER_VERSION_ATTRIBUTE_TYPE', 'record Version : LPCSTR; end');
  CL.AddTypeS('TGopherVersionAttributeType', 'GOPHER_VERSION_ATTRIBUTE_TYPE');
  //CL.AddTypeS('LPGOPHER_VERSION_ATTRIBUTE_TYPE', 'PGopherVersionAttributeType');
  CL.AddTypeS('GOPHER_ABSTRACT_ATTRIBUTE_TYPE', 'record ShortAbstract : LPCSTR; AbstractFile : LPCSTR; end');
  CL.AddTypeS('TGopherAbstractAttributeType', 'GOPHER_ABSTRACT_ATTRIBUTE_TYPE');
  //CL.AddTypeS('LPGOPHER_ABSTRACT_ATTRIBUTE_TYPE', 'PGopherAbstractAttributeType');
  CL.AddTypeS('GOPHER_VIEW_ATTRIBUTE_TYPE', 'record ContentType : LPCSTR; Language : LPCSTR; Size : DWORD; end');
  CL.AddTypeS('TGopherViewAttributeType', 'GOPHER_VIEW_ATTRIBUTE_TYPE');
  //CL.AddTypeS('LPGOPHER_VIEW_ATTRIBUTE_TYPE', 'PGopherViewAttributeType');
  CL.AddTypeS('GOPHER_VERONICA_ATTRIBUTE_TYPE', 'record TreeWalk : BOOL; end');
  CL.AddTypeS('TGopherVeronicaAttributeType', 'GOPHER_VERONICA_ATTRIBUTE_TYPE');
  //CL.AddTypeS('LPGOPHER_VERONICA_ATTRIBUTE_TYPE', 'PGopherVeronicaAttributeType');
  CL.AddTypeS('GOPHER_ASK_ATTRIBUTE_TYPE', 'record QuestionType : LPCSTR; QuestionText : LPCSTR; end');
  CL.AddTypeS('TGopherAskAttributeType', 'GOPHER_ASK_ATTRIBUTE_TYPE');
  //CL.AddTypeS('LPGOPHER_ASK_ATTRIBUTE_TYPE', 'PGopherAskAttributeType');
  CL.AddTypeS('GOPHER_UNKNOWN_ATTRIBUTE_TYPE', 'record Text : LPCSTR; end');
  CL.AddTypeS('TGopherUnknownAttributeType', 'GOPHER_UNKNOWN_ATTRIBUTE_TYPE');
  //CL.AddTypeS('LPGOPHER_UNKNOWN_ATTRIBUTE_TYPE', 'PGopherUnknownAttributeType');
 CL.AddConstantN('MAX_GOPHER_CATEGORY_NAME','LongInt').SetInt( 128);
 CL.AddConstantN('MAX_GOPHER_ATTRIBUTE_NAME','LongInt').SetInt( 128);
 CL.AddConstantN('MIN_GOPHER_ATTRIBUTE_LENGTH','LongInt').SetInt( 256);
 CL.AddConstantN('GOPHER_INFO_CATEGORY','String').SetString( '+INFO');
 CL.AddConstantN('GOPHER_ADMIN_CATEGORY','String').SetString( '+ADMIN');
 CL.AddConstantN('GOPHER_VIEWS_CATEGORY','String').SetString( '+VIEWS');
 CL.AddConstantN('GOPHER_ABSTRACT_CATEGORY','String').SetString( '+ABSTRACT');
 CL.AddConstantN('GOPHER_VERONICA_CATEGORY','String').SetString( '+VERONICA');
 CL.AddConstantN('GOPHER_ADMIN_ATTRIBUTE','String').SetString( 'Admin');
 CL.AddConstantN('GOPHER_MOD_DATE_ATTRIBUTE','String').SetString( 'Mod-Date');
 CL.AddConstantN('GOPHER_TTL_ATTRIBUTE','String').SetString( 'TTL');
 CL.AddConstantN('GOPHER_SCORE_ATTRIBUTE','String').SetString( 'Score');
 CL.AddConstantN('GOPHER_RANGE_ATTRIBUTE','String').SetString( 'Score-range');
 CL.AddConstantN('GOPHER_SITE_ATTRIBUTE','String').SetString( 'Site');
 CL.AddConstantN('GOPHER_ORG_ATTRIBUTE','String').SetString( 'Org');
 CL.AddConstantN('GOPHER_LOCATION_ATTRIBUTE','String').SetString( 'Loc');
 CL.AddConstantN('GOPHER_GEOG_ATTRIBUTE','String').SetString( 'Geog');
 CL.AddConstantN('GOPHER_TIMEZONE_ATTRIBUTE','String').SetString( 'TZ');
 CL.AddConstantN('GOPHER_PROVIDER_ATTRIBUTE','String').SetString( 'Provider');
 CL.AddConstantN('GOPHER_VERSION_ATTRIBUTE','String').SetString( 'Version');
 CL.AddConstantN('GOPHER_ABSTRACT_ATTRIBUTE','String').SetString( 'Abstract');
 CL.AddConstantN('GOPHER_VIEW_ATTRIBUTE','String').SetString( 'View');
 CL.AddConstantN('GOPHER_TREEWALK_ATTRIBUTE','String').SetString( 'treewalk');
 CL.AddConstantN('GOPHER_ATTRIBUTE_ID_BASE','LongWord').SetUInt( $abcccc00);
 CL.AddConstantN('GOPHER_CATEGORY_ID_ALL','LongInt').SetInt( GOPHER_ATTRIBUTE_ID_BASE + 1);
 CL.AddConstantN('GOPHER_CATEGORY_ID_INFO','LongInt').SetInt( GOPHER_ATTRIBUTE_ID_BASE + 2);
 CL.AddConstantN('GOPHER_CATEGORY_ID_ADMIN','LongInt').SetInt( GOPHER_ATTRIBUTE_ID_BASE + 3);
 CL.AddConstantN('GOPHER_CATEGORY_ID_VIEWS','LongInt').SetInt( GOPHER_ATTRIBUTE_ID_BASE + 4);
 CL.AddConstantN('GOPHER_CATEGORY_ID_ABSTRACT','LongInt').SetInt( GOPHER_ATTRIBUTE_ID_BASE + 5);
 CL.AddConstantN('GOPHER_CATEGORY_ID_VERONICA','LongInt').SetInt( GOPHER_ATTRIBUTE_ID_BASE + 6);
 CL.AddConstantN('GOPHER_CATEGORY_ID_ASK','LongInt').SetInt( GOPHER_ATTRIBUTE_ID_BASE + 7);
 CL.AddConstantN('GOPHER_CATEGORY_ID_UNKNOWN','LongInt').SetInt( GOPHER_ATTRIBUTE_ID_BASE + 8);
 CL.AddConstantN('GOPHER_ATTRIBUTE_ID_ALL','LongInt').SetInt( GOPHER_ATTRIBUTE_ID_BASE + 9);
 CL.AddConstantN('GOPHER_ATTRIBUTE_ID_ADMIN','LongInt').SetInt( GOPHER_ATTRIBUTE_ID_BASE + 10);
 CL.AddConstantN('GOPHER_ATTRIBUTE_ID_MOD_DATE','LongInt').SetInt( GOPHER_ATTRIBUTE_ID_BASE + 11);
 CL.AddConstantN('GOPHER_ATTRIBUTE_ID_TTL','LongInt').SetInt( GOPHER_ATTRIBUTE_ID_BASE + 12);
 CL.AddConstantN('GOPHER_ATTRIBUTE_ID_SCORE','LongInt').SetInt( GOPHER_ATTRIBUTE_ID_BASE + 13);
 CL.AddConstantN('GOPHER_ATTRIBUTE_ID_RANGE','LongInt').SetInt( GOPHER_ATTRIBUTE_ID_BASE + 14);
 CL.AddConstantN('GOPHER_ATTRIBUTE_ID_SITE','LongInt').SetInt( GOPHER_ATTRIBUTE_ID_BASE + 15);
 CL.AddConstantN('GOPHER_ATTRIBUTE_ID_ORG','LongInt').SetInt( GOPHER_ATTRIBUTE_ID_BASE + 16);
 CL.AddConstantN('GOPHER_ATTRIBUTE_ID_LOCATION','LongInt').SetInt( GOPHER_ATTRIBUTE_ID_BASE + 17);
 CL.AddConstantN('GOPHER_ATTRIBUTE_ID_GEOG','LongInt').SetInt( GOPHER_ATTRIBUTE_ID_BASE + 18);
 CL.AddConstantN('GOPHER_ATTRIBUTE_ID_TIMEZONE','LongInt').SetInt( GOPHER_ATTRIBUTE_ID_BASE + 19);
 CL.AddConstantN('GOPHER_ATTRIBUTE_ID_PROVIDER','LongInt').SetInt( GOPHER_ATTRIBUTE_ID_BASE + 20);
 CL.AddConstantN('GOPHER_ATTRIBUTE_ID_VERSION','LongInt').SetInt( GOPHER_ATTRIBUTE_ID_BASE + 21);
 CL.AddConstantN('GOPHER_ATTRIBUTE_ID_ABSTRACT','LongInt').SetInt( GOPHER_ATTRIBUTE_ID_BASE + 22);
 CL.AddConstantN('GOPHER_ATTRIBUTE_ID_VIEW','LongInt').SetInt( GOPHER_ATTRIBUTE_ID_BASE + 23);
 CL.AddConstantN('GOPHER_ATTRIBUTE_ID_TREEWALK','LongInt').SetInt( GOPHER_ATTRIBUTE_ID_BASE + 24);
 CL.AddConstantN('GOPHER_ATTRIBUTE_ID_UNKNOWN','LongInt').SetInt( GOPHER_ATTRIBUTE_ID_BASE + 25);
 CL.AddDelphiFunction('Function GopherCreateLocator( lpszHost : PChar; nServerPort : INTERNET_PORT; lpszDisplayString : PChar; lpszSelectorString : PChar; dwGopherType : DWORD; lpszLocator : PChar; var lpdwBufferLength : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function GopherCreateLocatorA( lpszHost : PAnsiChar; nServerPort : INTERNET_PORT; lpszDisplayString : PAnsiChar; lpszSelectorString : PAnsiChar; dwGopherType : DWORD; lpszLocator : PAnsiChar; var lpdwBufferLength : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function GopherCreateLocatorW( lpszHost : PWideChar; nServerPort : INTERNET_PORT; lpszDisplayString : PWideChar; lpszSelectorString : PWideChar; dwGopherType : DWORD; lpszLocator : PWideChar; var lpdwBufferLength : DWORD) : BOOL');
 CL.AddDelphiFunction('Function GopherGetLocatorType( lpszLocator : PChar; var lpdwGopherType : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function GopherGetLocatorTypeA( lpszLocator : PAnsiChar; var lpdwGopherType : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function GopherGetLocatorTypeW( lpszLocator : PWideChar; var lpdwGopherType : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function GopherFindFirstFile( hConnect : HINTERNET; lpszLocator : PChar; lpszSearchString : PChar; var lpFindData : TGopherFindData; dwFlags : DWORD; dwContext : DWORD) : HINTERNET');
 //CL.AddDelphiFunction('Function GopherFindFirstFileA( hConnect : HINTERNET; lpszLocator : PAnsiChar; lpszSearchString : PAnsiChar; var lpFindData : TGopherFindDataA; dwFlags : DWORD; dwContext : DWORD) : HINTERNET');
 //CL.AddDelphiFunction('Function GopherFindFirstFileW( hConnect : HINTERNET; lpszLocator : PWideChar; lpszSearchString : PWideChar; var lpFindData : TGopherFindDataW; dwFlags : DWORD; dwContext : DWORD) : HINTERNET');
 CL.AddDelphiFunction('Function GopherOpenFile( hConnect : HINTERNET; lpszLocator : PChar; lpszView : PChar; dwFlags : DWORD; dwContext : DWORD) : HINTERNET');
 //CL.AddDelphiFunction('Function GopherOpenFileA( hConnect : HINTERNET; lpszLocator : PAnsiChar; lpszView : PAnsiChar; dwFlags : DWORD; dwContext : DWORD) : HINTERNET');
 //CL.AddDelphiFunction('Function GopherOpenFileW( hConnect : HINTERNET; lpszLocator : PWideChar; lpszView : PWideChar; dwFlags : DWORD; dwContext : DWORD) : HINTERNET');
  CL.AddTypeS('GOPHER_ATTRIBUTE_ENUMERATOR', 'TFarProc');
  CL.AddTypeS('TFNGopherAttributeEnumerator', 'GOPHER_ATTRIBUTE_ENUMERATOR');
 //CL.AddDelphiFunction('Function GopherGetAttribute( hConnect : HINTERNET; lpszLocator : PChar; lpszAttributeName : PChar; lpBuffer : Pointer; dwBufferLength : DWORD; var lpdwCharactersReturned : DWORD;'+
  //'lpfnEnumerator : PFNGopherAttributeEnumerator; dwContext : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function GopherGetAttributeA( hConnect : HINTERNET; lpszLocator : PAnsiChar; lpszAttributeName : PAnsiChar; lpBuffer : Pointer; dwBufferLength : DWORD; var lpdwCharactersReturned : DWORD; lpfnEnumerator : PFNGopherAttributeEnumerator; dwContext : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function GopherGetAttributeW( hConnect : HINTERNET; lpszLocator : PWideChar; lpszAttributeName : PWideChar; lpBuffer : Pointer; dwBufferLength : DWORD; var lpdwCharactersReturned : DWORD; lpfnEnumerator : PFNGopherAttributeEnumerator; dwContext : DWORD) : BOOL');
 CL.AddConstantN('HTTP_MAJOR_VERSION','LongInt').SetInt( 1);
 CL.AddConstantN('HTTP_MINOR_VERSION','LongInt').SetInt( 0);
 CL.AddConstantN('HTTP_VERSION','String').SetString( 'HTTP/1.0');
 CL.AddConstantN('HTTP_QUERY_MIME_VERSION','LongInt').SetInt( 0);
 CL.AddConstantN('HTTP_QUERY_CONTENT_TYPE','LongInt').SetInt( 1);
 CL.AddConstantN('HTTP_QUERY_CONTENT_TRANSFER_ENCODING','LongInt').SetInt( 2);
 CL.AddConstantN('HTTP_QUERY_CONTENT_ID','LongInt').SetInt( 3);
 CL.AddConstantN('HTTP_QUERY_CONTENT_DESCRIPTION','LongInt').SetInt( 4);
 CL.AddConstantN('HTTP_QUERY_CONTENT_LENGTH','LongInt').SetInt( 5);
 CL.AddConstantN('HTTP_QUERY_CONTENT_LANGUAGE','LongInt').SetInt( 6);
 CL.AddConstantN('HTTP_QUERY_ALLOW','LongInt').SetInt( 7);
 CL.AddConstantN('HTTP_QUERY_PUBLIC','LongInt').SetInt( 8);
 CL.AddConstantN('HTTP_QUERY_DATE','LongInt').SetInt( 9);
 CL.AddConstantN('HTTP_QUERY_EXPIRES','LongInt').SetInt( 10);
 CL.AddConstantN('HTTP_QUERY_LAST_MODIFIED','LongInt').SetInt( 11);
 CL.AddConstantN('HTTP_QUERY_MESSAGE_ID','LongInt').SetInt( 12);
 CL.AddConstantN('HTTP_QUERY_URI','LongInt').SetInt( 13);
 CL.AddConstantN('HTTP_QUERY_DERIVED_FROM','LongInt').SetInt( 14);
 CL.AddConstantN('HTTP_QUERY_COST','LongInt').SetInt( 15);
 CL.AddConstantN('HTTP_QUERY_LINK','LongInt').SetInt( 16);
 CL.AddConstantN('HTTP_QUERY_PRAGMA','LongInt').SetInt( 17);
 CL.AddConstantN('HTTP_QUERY_VERSION','LongInt').SetInt( 18);
 CL.AddConstantN('HTTP_QUERY_STATUS_CODE','LongInt').SetInt( 19);
 CL.AddConstantN('HTTP_QUERY_STATUS_TEXT','LongInt').SetInt( 20);
 CL.AddConstantN('HTTP_QUERY_RAW_HEADERS','LongInt').SetInt( 21);
 CL.AddConstantN('HTTP_QUERY_RAW_HEADERS_CRLF','LongInt').SetInt( 22);
 CL.AddConstantN('HTTP_QUERY_CONNECTION','LongInt').SetInt( 23);
 CL.AddConstantN('HTTP_QUERY_ACCEPT','LongInt').SetInt( 24);
 CL.AddConstantN('HTTP_QUERY_ACCEPT_CHARSET','LongInt').SetInt( 25);
 CL.AddConstantN('HTTP_QUERY_ACCEPT_ENCODING','LongInt').SetInt( 26);
 CL.AddConstantN('HTTP_QUERY_ACCEPT_LANGUAGE','LongInt').SetInt( 27);
 CL.AddConstantN('HTTP_QUERY_AUTHORIZATION','LongInt').SetInt( 28);
 CL.AddConstantN('HTTP_QUERY_CONTENT_ENCODING','LongInt').SetInt( 29);
 CL.AddConstantN('HTTP_QUERY_FORWARDED','LongInt').SetInt( 30);
 CL.AddConstantN('HTTP_QUERY_FROM','LongInt').SetInt( 31);
 CL.AddConstantN('HTTP_QUERY_IF_MODIFIED_SINCE','LongInt').SetInt( 32);
 CL.AddConstantN('HTTP_QUERY_LOCATION','LongInt').SetInt( 33);
 CL.AddConstantN('HTTP_QUERY_ORIG_URI','LongInt').SetInt( 34);
 CL.AddConstantN('HTTP_QUERY_REFERER','LongInt').SetInt( 35);
 CL.AddConstantN('HTTP_QUERY_RETRY_AFTER','LongInt').SetInt( 36);
 CL.AddConstantN('HTTP_QUERY_SERVER','LongInt').SetInt( 37);
 CL.AddConstantN('HTTP_QUERY_TITLE','LongInt').SetInt( 38);
 CL.AddConstantN('HTTP_QUERY_USER_AGENT','LongInt').SetInt( 39);
 CL.AddConstantN('HTTP_QUERY_WWW_AUTHENTICATE','LongInt').SetInt( 40);
 CL.AddConstantN('HTTP_QUERY_PROXY_AUTHENTICATE','LongInt').SetInt( 41);
 CL.AddConstantN('HTTP_QUERY_ACCEPT_RANGES','LongInt').SetInt( 42);
 CL.AddConstantN('HTTP_QUERY_SET_COOKIE','LongInt').SetInt( 43);
 CL.AddConstantN('HTTP_QUERY_COOKIE','LongInt').SetInt( 44);
 CL.AddConstantN('HTTP_QUERY_REQUEST_METHOD','LongInt').SetInt( 45);
 CL.AddConstantN('HTTP_QUERY_REFRESH','LongInt').SetInt( 46);
 CL.AddConstantN('HTTP_QUERY_CONTENT_DISPOSITION','LongInt').SetInt( 47);
 CL.AddConstantN('HTTP_QUERY_AGE','LongInt').SetInt( 48);
 CL.AddConstantN('HTTP_QUERY_CACHE_CONTROL','LongInt').SetInt( 49);
 CL.AddConstantN('HTTP_QUERY_CONTENT_BASE','LongInt').SetInt( 50);
 CL.AddConstantN('HTTP_QUERY_CONTENT_LOCATION','LongInt').SetInt( 51);
 CL.AddConstantN('HTTP_QUERY_CONTENT_MD5','LongInt').SetInt( 52);
 CL.AddConstantN('HTTP_QUERY_CONTENT_RANGE','LongInt').SetInt( 53);
 CL.AddConstantN('HTTP_QUERY_ETAG','LongInt').SetInt( 54);
 CL.AddConstantN('HTTP_QUERY_HOST','LongInt').SetInt( 55);
 CL.AddConstantN('HTTP_QUERY_IF_MATCH','LongInt').SetInt( 56);
 CL.AddConstantN('HTTP_QUERY_IF_NONE_MATCH','LongInt').SetInt( 57);
 CL.AddConstantN('HTTP_QUERY_IF_RANGE','LongInt').SetInt( 58);
 CL.AddConstantN('HTTP_QUERY_IF_UNMODIFIED_SINCE','LongInt').SetInt( 59);
 CL.AddConstantN('HTTP_QUERY_MAX_FORWARDS','LongInt').SetInt( 60);
 CL.AddConstantN('HTTP_QUERY_PROXY_AUTHORIZATION','LongInt').SetInt( 61);
 CL.AddConstantN('HTTP_QUERY_RANGE','LongInt').SetInt( 62);
 CL.AddConstantN('HTTP_QUERY_TRANSFER_ENCODING','LongInt').SetInt( 63);
 CL.AddConstantN('HTTP_QUERY_UPGRADE','LongInt').SetInt( 64);
 CL.AddConstantN('HTTP_QUERY_VARY','LongInt').SetInt( 65);
 CL.AddConstantN('HTTP_QUERY_VIA','LongInt').SetInt( 66);
 CL.AddConstantN('HTTP_QUERY_WARNING','LongInt').SetInt( 67);
 CL.AddConstantN('HTTP_QUERY_MAX','LongInt').SetInt( 67);
 CL.AddConstantN('HTTP_QUERY_CUSTOM','LongInt').SetInt( 65535);
 CL.AddConstantN('HTTP_QUERY_FLAG_REQUEST_HEADERS','LongWord').SetUInt( $80000000);
 CL.AddConstantN('HTTP_QUERY_FLAG_SYSTEMTIME','LongWord').SetUInt( $40000000);
 CL.AddConstantN('HTTP_QUERY_FLAG_NUMBER','LongWord').SetUInt( $20000000);
 CL.AddConstantN('HTTP_QUERY_FLAG_COALESCE','LongWord').SetUInt( $10000000);
 CL.AddConstantN('HTTP_STATUS_CONTINUE','LongInt').SetInt( 100);
 CL.AddConstantN('HTTP_STATUS_SWITCH_PROTOCOLS','LongInt').SetInt( 101);
 CL.AddConstantN('HTTP_STATUS_OK','LongInt').SetInt( 200);
 CL.AddConstantN('HTTP_STATUS_CREATED','LongInt').SetInt( 201);
 CL.AddConstantN('HTTP_STATUS_ACCEPTED','LongInt').SetInt( 202);
 CL.AddConstantN('HTTP_STATUS_PARTIAL','LongInt').SetInt( 203);
 CL.AddConstantN('HTTP_STATUS_NO_CONTENT','LongInt').SetInt( 204);
 CL.AddConstantN('HTTP_STATUS_RESET_CONTENT','LongInt').SetInt( 205);
 CL.AddConstantN('HTTP_STATUS_PARTIAL_CONTENT','LongInt').SetInt( 206);
 CL.AddConstantN('HTTP_STATUS_AMBIGUOUS','LongInt').SetInt( 300);
 CL.AddConstantN('HTTP_STATUS_MOVED','LongInt').SetInt( 301);
 CL.AddConstantN('HTTP_STATUS_REDIRECT','LongInt').SetInt( 302);
 CL.AddConstantN('HTTP_STATUS_REDIRECT_METHOD','LongInt').SetInt( 303);
 CL.AddConstantN('HTTP_STATUS_NOT_MODIFIED','LongInt').SetInt( 304);
 CL.AddConstantN('HTTP_STATUS_USE_PROXY','LongInt').SetInt( 305);
 CL.AddConstantN('HTTP_STATUS_REDIRECT_KEEP_VERB','LongInt').SetInt( 307);
 CL.AddConstantN('HTTP_STATUS_BAD_REQUEST','LongInt').SetInt( 400);
 CL.AddConstantN('HTTP_STATUS_DENIED','LongInt').SetInt( 401);
 CL.AddConstantN('HTTP_STATUS_PAYMENT_REQ','LongInt').SetInt( 402);
 CL.AddConstantN('HTTP_STATUS_FORBIDDEN','LongInt').SetInt( 403);
 CL.AddConstantN('HTTP_STATUS_NOT_FOUND','LongInt').SetInt( 404);
 CL.AddConstantN('HTTP_STATUS_BAD_METHOD','LongInt').SetInt( 405);
 CL.AddConstantN('HTTP_STATUS_NONE_ACCEPTABLE','LongInt').SetInt( 406);
 CL.AddConstantN('HTTP_STATUS_PROXY_AUTH_REQ','LongInt').SetInt( 407);
 CL.AddConstantN('HTTP_STATUS_REQUEST_TIMEOUT','LongInt').SetInt( 408);
 CL.AddConstantN('HTTP_STATUS_CONFLICT','LongInt').SetInt( 409);
 CL.AddConstantN('HTTP_STATUS_GONE','LongInt').SetInt( 410);
 CL.AddConstantN('HTTP_STATUS_AUTH_REFUSED','LongInt').SetInt( 411);
 CL.AddConstantN('HTTP_STATUS_PRECOND_FAILED','LongInt').SetInt( 412);
 CL.AddConstantN('HTTP_STATUS_REQUEST_TOO_LARGE','LongInt').SetInt( 413);
 CL.AddConstantN('HTTP_STATUS_URI_TOO_LONG','LongInt').SetInt( 414);
 CL.AddConstantN('HTTP_STATUS_UNSUPPORTED_MEDIA','LongInt').SetInt( 415);
 CL.AddConstantN('HTTP_STATUS_SERVER_ERROR','LongInt').SetInt( 500);
 CL.AddConstantN('HTTP_STATUS_NOT_SUPPORTED','LongInt').SetInt( 501);
 CL.AddConstantN('HTTP_STATUS_BAD_GATEWAY','LongInt').SetInt( 502);
 CL.AddConstantN('HTTP_STATUS_SERVICE_UNAVAIL','LongInt').SetInt( 503);
 CL.AddConstantN('HTTP_STATUS_GATEWAY_TIMEOUT','LongInt').SetInt( 504);
 CL.AddConstantN('HTTP_STATUS_VERSION_NOT_SUP','LongInt').SetInt( 505);
 //7CL.AddConstantN('HTTP_STATUS_FIRST','').SetString( HTTP_STATUS_CONTINUE);
 //CL.AddConstantN('HTTP_STATUS_LAST','').SetString( HTTP_STATUS_VERSION_NOT_SUP);
 CL.AddDelphiFunction('Function HttpOpenRequest( hConnect : HINTERNET; lpszVerb : PChar; lpszObjectName : PChar; lpszVersion : PChar; lpszReferrer : PChar; lplpszAcceptTypes : PLPSTR; dwFlags : DWORD; dwContext : DWORD) : HINTERNET');
 //CL.AddDelphiFunction('Function HttpOpenRequestA( hConnect : HINTERNET; lpszVerb : PAnsiChar; lpszObjectName : PAnsiChar; lpszVersion : PAnsiChar; lpszReferrer : PAnsiChar; lplpszAcceptTypes : PLPSTR; dwFlags : DWORD; dwContext : DWORD) : HINTERNET');
 //CL.AddDelphiFunction('Function HttpOpenRequestW( hConnect : HINTERNET; lpszVerb : PWideChar; lpszObjectName : PWideChar; lpszVersion : PWideChar; lpszReferrer : PWideChar; lplpszAcceptTypes : PLPWSTR; dwFlags : DWORD; dwContext : DWORD) : HINTERNET');
 CL.AddDelphiFunction('Function HttpAddRequestHeaders( hRequest : HINTERNET; lpszHeaders : PChar; dwHeadersLength : DWORD; dwModifiers : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function HttpAddRequestHeadersA( hRequest : HINTERNET; lpszHeaders : PAnsiChar; dwHeadersLength : DWORD; dwModifiers : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function HttpAddRequestHeadersW( hRequest : HINTERNET; lpszHeaders : PWideChar; dwHeadersLength : DWORD; dwModifiers : DWORD) : BOOL');
 CL.AddConstantN('HTTP_ADDREQ_INDEX_MASK','LongWord').SetUInt( $0000FFFF);
 CL.AddConstantN('HTTP_ADDREQ_FLAGS_MASK','LongWord').SetUInt( $FFFF0000);
 CL.AddConstantN('HTTP_ADDREQ_FLAG_ADD_IF_NEW','LongWord').SetUInt( $10000000);
 CL.AddConstantN('HTTP_ADDREQ_FLAG_ADD','LongWord').SetUInt( $20000000);
 CL.AddConstantN('HTTP_ADDREQ_FLAG_COALESCE_WITH_COMMA','LongWord').SetUInt( $40000000);
 CL.AddConstantN('HTTP_ADDREQ_FLAG_COALESCE_WITH_SEMICOLON','LongWord').SetUInt( $01000000);
 //CL.AddConstantN('HTTP_ADDREQ_FLAG_COALESCE','').SetString( HTTP_ADDREQ_FLAG_COALESCE_WITH_COMMA);
 CL.AddConstantN('HTTP_ADDREQ_FLAG_REPLACE','LongWord').SetUInt( $80000000);
 CL.AddDelphiFunction('Function HttpSendRequest( hRequest : HINTERNET; lpszHeaders : PChar; dwHeadersLength : DWORD; lpOptional : Tobject; dwOptionalLength : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function HttpSendRequestA( hRequest : HINTERNET; lpszHeaders : PAnsiChar; dwHeadersLength : DWORD; lpOptional : Pointer; dwOptionalLength : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function HttpSendRequestW( hRequest : HINTERNET; lpszHeaders : PWideChar; dwHeadersLength : DWORD; lpOptional : Pointer; dwOptionalLength : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function HttpSendRequestEx( hRequest : HINTERNET; lpBuffersIn : PInternetBuffers; lpBuffersOut : PInternetBuffers; dwFlags : DWORD; dwContext : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function HttpSendRequestExA( hRequest : HINTERNET; lpBuffersIn : PInternetBuffers; lpBuffersOut : PInternetBuffers; dwFlags : DWORD; dwContext : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function HttpSendRequestExW( hRequest : HINTERNET; lpBuffersIn : PInternetBuffers; lpBuffersOut : PInternetBuffers; dwFlags : DWORD; dwContext : DWORD) : BOOL');
 CL.AddConstantN('HSR_ASYNC','longword').SetUint(1);
 CL.AddConstantN('HSR_SYNC','longword').Setuint(4);
 CL.AddConstantN('HSR_USE_CONTEXT','longword').Setuint(8);
 CL.AddConstantN('HSR_INITIATE','LongWord').SetUInt( $00000008);
 CL.AddConstantN('HSR_DOWNLOAD','LongWord').SetUInt( $00000010);
 CL.AddConstantN('HSR_CHUNKED','LongWord').SetUInt( $00000020);
   CL.AddTypeS('INTERNET_CACHE_ENTRY_INFOA', 'record dwStructSize : DWORD; lpszS'
   +'ourceUrlName : PChar; lpszLocalFileName : PChar; CacheEntryType : '
   +'DWORD; dwUseCount : DWORD; dwHitRate : DWORD; dwSizeLow : DWORD; dwSizeHig'
   +'h : DWORD; LastModifiedTime : TFileTime; ExpireTime : TFileTime; LastAcces'
   +'sTime : TFileTime; LastSyncTime : TFileTime; lpHeaderInfo : BYTE; dwHeade'
   +'rInfoSize : DWORD; lpszFileExtension : PChar; dwReserved : DWORD; end');
   CL.AddTypeS('TINTERNETCACHEENTRYINFO', 'INTERNET_CACHE_ENTRY_INFOA');

 //CL.AddDelphiFunction('Function HttpEndRequest( hRequest : HINTERNET; lpBuffersOut : PInternetBuffers; dwFlags : DWORD; dwContext : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function HttpEndRequestA( hRequest : HINTERNET; lpBuffersOut : PInternetBuffers; dwFlags : DWORD; dwContext : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function HttpEndRequestW( hRequest : HINTERNET; lpBuffersOut : PInternetBuffers; dwFlags : DWORD; dwContext : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function HttpQueryInfo( hRequest : HINTERNET; dwInfoLevel : DWORD; lpvBuffer : Pointer; var lpdwBufferLength : DWORD; var lpdwReserved : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function HttpQueryInfoA( hRequest : HINTERNET; dwInfoLevel : DWORD; lpvBuffer : Pointer; var lpdwBufferLength : DWORD; var lpdwReserved : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function HttpQueryInfoW( hRequest : HINTERNET; dwInfoLevel : DWORD; lpvBuffer : Pointer; var lpdwBufferLength : DWORD; var lpdwReserved : DWORD) : BOOL');
 CL.AddDelphiFunction('Function InternetSetCookie( lpszUrl, lpszCookieName, lpszCookieData : PChar) : BOOL');
 //CL.AddDelphiFunction('Function InternetSetCookieA( lpszUrl, lpszCookieName, lpszCookieData : PAnsiChar) : BOOL');
 //CL.AddDelphiFunction('Function InternetSetCookieW( lpszUrl, lpszCookieName, lpszCookieData : PWideChar) : BOOL');
 CL.AddDelphiFunction('Function InternetGetCookie( lpszUrl, lpszCookieName, lpszCookieData : PChar; var lpdwSize : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function InternetGetCookieA( lpszUrl, lpszCookieName, lpszCookieData : PAnsiChar; var lpdwSize : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function InternetGetCookieW( lpszUrl, lpszCookieName, lpszCookieData : PWideChar; var lpdwSize : DWORD) : BOOL');
 CL.AddDelphiFunction('Function InternetAttemptConnect( dwReserved : DWORD) : DWORD');
 CL.AddDelphiFunction('Function InternetCheckConnection( lpszUrl : PChar; dwFlags : DWORD; dwReserved : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function InternetCheckConnectionA( lpszUrl : PAnsiChar; dwFlags : DWORD; dwReserved : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function InternetCheckConnectionW( lpszUrl : PAnsiChar; dwFlags : DWORD; dwReserved : DWORD) : BOOL');
 CL.AddConstantN('FLAGS_ERROR_UI_FILTER_FOR_ERRORS','LongWord').SetUInt( $01);
 CL.AddConstantN('FLAGS_ERROR_UI_FLAGS_CHANGE_OPTIONS','LongWord').SetUInt( $02);
 CL.AddConstantN('FLAGS_ERROR_UI_FLAGS_GENERATE_DATA','LongWord').SetUInt( $04);
 CL.AddConstantN('FLAGS_ERROR_UI_FLAGS_NO_UI','LongWord').SetUInt( $08);
 CL.AddConstantN('FLAGS_ERROR_UI_SERIALIZE_DIALOGS','LongWord').SetUInt( $10);
 //CL.AddDelphiFunction('Function InternetAuthNotifyCallback( dwContext : DWORD; dwReturn : DWORD; lpReserved : Pointer) : DWORD');
 CL.AddDelphiFunction('Function InternetErrorDlg( hWnd : HWND; hRequest : HINTERNET; dwError, dwFlags : DWORD; var lppvData : TObject) : DWORD');
 CL.AddDelphiFunction('Function InternetConfirmZoneCrossing( hWnd : HWND; szUrlPrev, szUrlNew : LPSTR; bPost : BOOL) : DWORD');
 CL.AddConstantN('INTERNET_ERROR_BASE','LongInt').SetInt( 12000);
 CL.AddConstantN('ERROR_INTERNET_OUT_OF_HANDLES','LongInt').SetInt( INTERNET_ERROR_BASE + 1);
 CL.AddConstantN('ERROR_INTERNET_TIMEOUT','LongInt').SetInt( INTERNET_ERROR_BASE + 2);
 CL.AddConstantN('ERROR_INTERNET_EXTENDED_ERROR','LongInt').SetInt( INTERNET_ERROR_BASE + 3);
 CL.AddConstantN('ERROR_INTERNET_INTERNAL_ERROR','LongInt').SetInt( INTERNET_ERROR_BASE + 4);
 CL.AddConstantN('ERROR_INTERNET_INVALID_URL','LongInt').SetInt( INTERNET_ERROR_BASE + 5);
 CL.AddConstantN('ERROR_INTERNET_UNRECOGNIZED_SCHEME','LongInt').SetInt( INTERNET_ERROR_BASE + 6);
 CL.AddConstantN('ERROR_INTERNET_NAME_NOT_RESOLVED','LongInt').SetInt( INTERNET_ERROR_BASE + 7);
 CL.AddConstantN('ERROR_INTERNET_PROTOCOL_NOT_FOUND','LongInt').SetInt( INTERNET_ERROR_BASE + 8);
 CL.AddConstantN('ERROR_INTERNET_INVALID_OPTION','LongInt').SetInt( INTERNET_ERROR_BASE + 9);
 CL.AddConstantN('ERROR_INTERNET_BAD_OPTION_LENGTH','LongInt').SetInt( INTERNET_ERROR_BASE + 10);
 CL.AddConstantN('ERROR_INTERNET_OPTION_NOT_SETTABLE','LongInt').SetInt( INTERNET_ERROR_BASE + 11);
 CL.AddConstantN('ERROR_INTERNET_SHUTDOWN','LongInt').SetInt( INTERNET_ERROR_BASE + 12);
 CL.AddConstantN('ERROR_INTERNET_INCORRECT_USER_NAME','LongInt').SetInt( INTERNET_ERROR_BASE + 13);
 CL.AddConstantN('ERROR_INTERNET_INCORRECT_PASSWORD','LongInt').SetInt( INTERNET_ERROR_BASE + 14);
 CL.AddConstantN('ERROR_INTERNET_LOGIN_FAILURE','LongInt').SetInt( INTERNET_ERROR_BASE + 15);
 CL.AddConstantN('ERROR_INTERNET_INVALID_OPERATION','LongInt').SetInt( INTERNET_ERROR_BASE + 16);
 CL.AddConstantN('ERROR_INTERNET_OPERATION_CANCELLED','LongInt').SetInt( INTERNET_ERROR_BASE + 17);
 CL.AddConstantN('ERROR_INTERNET_INCORRECT_HANDLE_TYPE','LongInt').SetInt( INTERNET_ERROR_BASE + 18);
 CL.AddConstantN('ERROR_INTERNET_INCORRECT_HANDLE_STATE','LongInt').SetInt( INTERNET_ERROR_BASE + 19);
 CL.AddConstantN('ERROR_INTERNET_NOT_PROXY_REQUEST','LongInt').SetInt( INTERNET_ERROR_BASE + 20);
 CL.AddConstantN('ERROR_INTERNET_REGISTRY_VALUE_NOT_FOUND','LongInt').SetInt( INTERNET_ERROR_BASE + 21);
 CL.AddConstantN('ERROR_INTERNET_BAD_REGISTRY_PARAMETER','LongInt').SetInt( INTERNET_ERROR_BASE + 22);
 CL.AddConstantN('ERROR_INTERNET_NO_DIRECT_ACCESS','LongInt').SetInt( INTERNET_ERROR_BASE + 23);
 CL.AddConstantN('ERROR_INTERNET_NO_CONTEXT','LongInt').SetInt( INTERNET_ERROR_BASE + 24);
 CL.AddConstantN('ERROR_INTERNET_NO_CALLBACK','LongInt').SetInt( INTERNET_ERROR_BASE + 25);
 CL.AddConstantN('ERROR_INTERNET_REQUEST_PENDING','LongInt').SetInt( INTERNET_ERROR_BASE + 26);
 CL.AddConstantN('ERROR_INTERNET_INCORRECT_FORMAT','LongInt').SetInt( INTERNET_ERROR_BASE + 27);
 CL.AddConstantN('ERROR_INTERNET_ITEM_NOT_FOUND','LongInt').SetInt( INTERNET_ERROR_BASE + 28);
 CL.AddConstantN('ERROR_INTERNET_CANNOT_CONNECT','LongInt').SetInt( INTERNET_ERROR_BASE + 29);
 CL.AddConstantN('ERROR_INTERNET_CONNECTION_ABORTED','LongInt').SetInt( INTERNET_ERROR_BASE + 30);
 CL.AddConstantN('ERROR_INTERNET_CONNECTION_RESET','LongInt').SetInt( INTERNET_ERROR_BASE + 31);
 CL.AddConstantN('ERROR_INTERNET_FORCE_RETRY','LongInt').SetInt( INTERNET_ERROR_BASE + 32);
 CL.AddConstantN('ERROR_INTERNET_INVALID_PROXY_REQUEST','LongInt').SetInt( INTERNET_ERROR_BASE + 33);
 CL.AddConstantN('ERROR_INTERNET_HANDLE_EXISTS','LongInt').SetInt( INTERNET_ERROR_BASE + 36);
 CL.AddConstantN('ERROR_INTERNET_SEC_CERT_DATE_INVALID','LongInt').SetInt( INTERNET_ERROR_BASE + 37);
 CL.AddConstantN('ERROR_INTERNET_SEC_CERT_CN_INVALID','LongInt').SetInt( INTERNET_ERROR_BASE + 38);
 CL.AddConstantN('ERROR_INTERNET_HTTP_TO_HTTPS_ON_REDIR','LongInt').SetInt( INTERNET_ERROR_BASE + 39);
 CL.AddConstantN('ERROR_INTERNET_HTTPS_TO_HTTP_ON_REDIR','LongInt').SetInt( INTERNET_ERROR_BASE + 40);
 CL.AddConstantN('ERROR_INTERNET_MIXED_SECURITY','LongInt').SetInt( INTERNET_ERROR_BASE + 41);
 CL.AddConstantN('ERROR_INTERNET_CHG_POST_IS_NON_SECURE','LongInt').SetInt( INTERNET_ERROR_BASE + 42);
 CL.AddConstantN('ERROR_INTERNET_POST_IS_NON_SECURE','LongInt').SetInt( INTERNET_ERROR_BASE + 43);
 CL.AddConstantN('ERROR_INTERNET_CLIENT_AUTH_CERT_NEEDED','LongInt').SetInt( INTERNET_ERROR_BASE + 44);
 CL.AddConstantN('ERROR_INTERNET_INVALID_CA','LongInt').SetInt( INTERNET_ERROR_BASE + 45);
 CL.AddConstantN('ERROR_INTERNET_CLIENT_AUTH_NOT_SETUP','LongInt').SetInt( INTERNET_ERROR_BASE + 46);
 CL.AddConstantN('ERROR_INTERNET_ASYNC_THREAD_FAILED','LongInt').SetInt( INTERNET_ERROR_BASE + 47);
 CL.AddConstantN('ERROR_INTERNET_REDIRECT_SCHEME_CHANGE','LongInt').SetInt( INTERNET_ERROR_BASE + 48);
 CL.AddConstantN('ERROR_INTERNET_DIALOG_PENDING','LongInt').SetInt( INTERNET_ERROR_BASE + 49);
 CL.AddConstantN('ERROR_INTERNET_RETRY_DIALOG','LongInt').SetInt( INTERNET_ERROR_BASE + 50);
 CL.AddConstantN('ERROR_INTERNET_HTTPS_HTTP_SUBMIT_REDIR','LongInt').SetInt( INTERNET_ERROR_BASE + 52);
 CL.AddConstantN('ERROR_INTERNET_INSERT_CDROM','LongInt').SetInt( INTERNET_ERROR_BASE + 53);
 CL.AddConstantN('ERROR_FTP_TRANSFER_IN_PROGRESS','LongInt').SetInt( INTERNET_ERROR_BASE + 110);
 CL.AddConstantN('ERROR_FTP_DROPPED','LongInt').SetInt( INTERNET_ERROR_BASE + 111);
 CL.AddConstantN('ERROR_FTP_NO_PASSIVE_MODE','LongInt').SetInt( INTERNET_ERROR_BASE + 112);
 CL.AddConstantN('ERROR_GOPHER_PROTOCOL_ERROR','LongInt').SetInt( INTERNET_ERROR_BASE + 130);
 CL.AddConstantN('ERROR_GOPHER_NOT_FILE','LongInt').SetInt( INTERNET_ERROR_BASE + 131);
 CL.AddConstantN('ERROR_GOPHER_DATA_ERROR','LongInt').SetInt( INTERNET_ERROR_BASE + 132);
 CL.AddConstantN('ERROR_GOPHER_END_OF_DATA','LongInt').SetInt( INTERNET_ERROR_BASE + 133);
 CL.AddConstantN('ERROR_GOPHER_INVALID_LOCATOR','LongInt').SetInt( INTERNET_ERROR_BASE + 134);
 CL.AddConstantN('ERROR_GOPHER_INCORRECT_LOCATOR_TYPE','LongInt').SetInt( INTERNET_ERROR_BASE + 135);
 CL.AddConstantN('ERROR_GOPHER_NOT_GOPHER_PLUS','LongInt').SetInt( INTERNET_ERROR_BASE + 136);
 CL.AddConstantN('ERROR_GOPHER_ATTRIBUTE_NOT_FOUND','LongInt').SetInt( INTERNET_ERROR_BASE + 137);
 CL.AddConstantN('ERROR_GOPHER_UNKNOWN_LOCATOR','LongInt').SetInt( INTERNET_ERROR_BASE + 138);
 CL.AddConstantN('ERROR_HTTP_HEADER_NOT_FOUND','LongInt').SetInt( INTERNET_ERROR_BASE + 150);
 CL.AddConstantN('ERROR_HTTP_DOWNLEVEL_SERVER','LongInt').SetInt( INTERNET_ERROR_BASE + 151);
 CL.AddConstantN('ERROR_HTTP_INVALID_SERVER_RESPONSE','LongInt').SetInt( INTERNET_ERROR_BASE + 152);
 CL.AddConstantN('ERROR_HTTP_INVALID_HEADER','LongInt').SetInt( INTERNET_ERROR_BASE + 153);
 CL.AddConstantN('ERROR_HTTP_INVALID_QUERY_REQUEST','LongInt').SetInt( INTERNET_ERROR_BASE + 154);
 CL.AddConstantN('ERROR_HTTP_HEADER_ALREADY_EXISTS','LongInt').SetInt( INTERNET_ERROR_BASE + 155);
 CL.AddConstantN('ERROR_HTTP_REDIRECT_FAILED','LongInt').SetInt( INTERNET_ERROR_BASE + 156);
 CL.AddConstantN('ERROR_HTTP_NOT_REDIRECTED','LongInt').SetInt( INTERNET_ERROR_BASE + 160);
 CL.AddConstantN('ERROR_HTTP_COOKIE_NEEDS_CONFIRMATION','LongInt').SetInt( INTERNET_ERROR_BASE + 161);
 CL.AddConstantN('ERROR_HTTP_COOKIE_DECLINED','LongInt').SetInt( INTERNET_ERROR_BASE + 162);
 CL.AddConstantN('ERROR_HTTP_REDIRECT_NEEDS_CONFIRMATION','LongInt').SetInt( INTERNET_ERROR_BASE + 168);
 CL.AddConstantN('ERROR_INTERNET_SECURITY_CHANNEL_ERROR','LongInt').SetInt( INTERNET_ERROR_BASE + 157);
 CL.AddConstantN('ERROR_INTERNET_UNABLE_TO_CACHE_FILE','LongInt').SetInt( INTERNET_ERROR_BASE + 158);
 CL.AddConstantN('ERROR_INTERNET_TCPIP_NOT_INSTALLED','LongInt').SetInt( INTERNET_ERROR_BASE + 159);
 CL.AddConstantN('ERROR_INTERNET_DISCONNECTED','LongInt').SetInt( INTERNET_ERROR_BASE + 163);
 CL.AddConstantN('ERROR_INTERNET_SERVER_UNREACHABLE','LongInt').SetInt( INTERNET_ERROR_BASE + 164);
 CL.AddConstantN('ERROR_INTERNET_PROXY_SERVER_UNREACHABLE','LongInt').SetInt( INTERNET_ERROR_BASE + 165);
 CL.AddConstantN('ERROR_INTERNET_BAD_AUTO_PROXY_SCRIPT','LongInt').SetInt( INTERNET_ERROR_BASE + 166);
 CL.AddConstantN('ERROR_INTERNET_UNABLE_TO_DOWNLOAD_SCRIPT','LongInt').SetInt( INTERNET_ERROR_BASE + 167);
 CL.AddConstantN('ERROR_INTERNET_SEC_INVALID_CERT','LongInt').SetInt( INTERNET_ERROR_BASE + 169);
 CL.AddConstantN('ERROR_INTERNET_SEC_CERT_REVOKED','LongInt').SetInt( INTERNET_ERROR_BASE + 170);
 CL.AddConstantN('ERROR_INTERNET_FAILED_DUETOSECURITYCHECK','LongInt').SetInt( INTERNET_ERROR_BASE + 171);
 //CL.AddConstantN('INTERNET_ERROR_LAST','').SetString( ERROR_INTERNET_FAILED_DUETOSECURITYCHECK);
 CL.AddConstantN('NORMAL_CACHE_ENTRY','LongWord').SetUInt( $00000001);
 CL.AddConstantN('STABLE_CACHE_ENTRY','LongWord').SetUInt( $00000002);
 CL.AddConstantN('STICKY_CACHE_ENTRY','LongWord').SetUInt( $00000004);
 CL.AddConstantN('COOKIE_CACHE_ENTRY','LongWord').SetUInt( $00100000);
 CL.AddConstantN('URLHISTORY_CACHE_ENTRY','LongWord').SetUInt( $00200000);
 CL.AddConstantN('TRACK_OFFLINE_CACHE_ENTRY','LongWord').SetUInt( $00000010);
 CL.AddConstantN('TRACK_ONLINE_CACHE_ENTRY','LongWord').SetUInt( $00000020);
 CL.AddConstantN('SPARSE_CACHE_ENTRY','LongWord').SetUInt( $00010000);
 CL.AddConstantN('OCX_CACHE_ENTRY','LongWord').SetUInt( $00020000);
 CL.AddConstantN('CACHE_ENTRY_ATTRIBUTE_FC','LongWord').SetUInt( $00000004);
 CL.AddConstantN('CACHE_ENTRY_HITRATE_FC','LongWord').SetUInt( $00000010);
 CL.AddConstantN('CACHE_ENTRY_MODTIME_FC','LongWord').SetUInt( $00000040);
 CL.AddConstantN('CACHE_ENTRY_EXPTIME_FC','LongWord').SetUInt( $00000080);
 CL.AddConstantN('CACHE_ENTRY_ACCTIME_FC','LongWord').SetUInt( $00000100);
 CL.AddConstantN('CACHE_ENTRY_SYNCTIME_FC','LongWord').SetUInt( $00000200);
 CL.AddConstantN('CACHE_ENTRY_HEADERINFO_FC','LongWord').SetUInt( $00000400);
 CL.AddConstantN('CACHE_ENTRY_EXEMPT_DELTA_FC','LongWord').SetUInt( $00000800);
  CL.AddTypeS('GROUPID', 'Int64');
 CL.AddDelphiFunction('Function CreateUrlCacheGroup( dwFlags : DWORD; lpReserved : TObject) : Int64');
 CL.AddDelphiFunction('Function DeleteUrlCacheGroup( GroupId : Int64; dwFlags : DWORD; lpReserved : TObject) : Bool');
 CL.AddConstantN('INTERNET_CACHE_GROUP_ADD','LongInt').SetInt( 0);
 CL.AddConstantN('INTERNET_CACHE_GROUP_REMOVE','LongInt').SetInt( 1);
 //CL.AddDelphiFunction('Function SetUrlCacheEntryGroup( lpszUrlName : LPCSTR; dwFlags : DWORD; GroupId : Int64; pbGroupAttributes : PChar; cbGroupAttributes : DWORD; lpReserved : Pointer) : Bool');
 //CL.AddDelphiFunction('Function FindNextUrlCacheEntryEx( hEnumHandle : THANDLE; lpFirstCacheEntryInfo : PInternetCacheEntryInfo; lpdwFirstCacheEntryInfoBufferSize : LPDWORD; lpGroupAttributes : Pointer; pcbGroupAttributes : LPDWORD; lpReserved : Pointer) : BOOL');
 //CL.AddDelphiFunction('Function FindNextUrlCacheEntryExA( hEnumHandle : THANDLE; lpFirstCacheEntryInfo : PInternetCacheEntryInfo; lpdwFirstCacheEntryInfoBufferSize : LPDWORD; lpGroupAttributes : Pointer; pcbGroupAttributes : LPDWORD; lpReserved : Pointer) : BOOL');
 //CL.AddDelphiFunction('Function FindNextUrlCacheEntryExW( hEnumHandle : THANDLE; lpFirstCacheEntryInfo : PInternetCacheEntryInfo; lpdwFirstCacheEntryInfoBufferSize : LPDWORD; lpGroupAttributes : Pointer; pcbGroupAttributes : LPDWORD; lpReserved : Pointer) : BOOL');
 CL.AddDelphiFunction('Function FindFirstUrlCacheEntry( lpszUrlSearchPattern : PChar; var lpFirstCacheEntryInfo : TInternetCacheEntryInfo; var lpdwFirstCacheEntryInfoBufferSize : DWORD) : THandle');
 //CL.AddDelphiFunction('Function FindFirstUrlCacheEntryA( lpszUrlSearchPattern : PAnsiChar; var lpFirstCacheEntryInfo : TInternetCacheEntryInfo; var lpdwFirstCacheEntryInfoBufferSize : DWORD) : THandle');
 //CL.AddDelphiFunction('Function FindFirstUrlCacheEntryW( lpszUrlSearchPattern : PAnsiChar; var lpFirstCacheEntryInfo : TInternetCacheEntryInfo; var lpdwFirstCacheEntryInfoBufferSize : DWORD) : THandle');
 CL.AddDelphiFunction('Function FindNextUrlCacheEntry( hEnumHandle : THandle; var lpNextCacheEntryInfo : TInternetCacheEntryInfo; var lpdwNextCacheEntryInfoBufferSize : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function FindNextUrlCacheEntryA( hEnumHandle : THandle; var lpNextCacheEntryInfo : TInternetCacheEntryInfo; var lpdwNextCacheEntryInfoBufferSize : DWORD) : BOOL');
 //CL.AddDelphiFunction('Function FindNextUrlCacheEntryW( hEnumHandle : THandle; var lpNextCacheEntryInfo : TInternetCacheEntryInfo; var lpdwNextCacheEntryInfoBufferSize : DWORD) : BOOL');
 CL.AddDelphiFunction('Function FindCloseUrlCache( hEnumHandle : THandle) : BOOL');
 CL.AddDelphiFunction('Function DeleteUrlCacheEntry( lpszUrlName : LPCSTR) : BOOL');
 CL.AddDelphiFunction('Function InternetDial( hwndParent : HWND; lpszConnectoid : Pchar; dwFlags : DWORD; lpdwConnection : DWORD; dwReserved : DWORD) : DWORD');
 CL.AddConstantN('INTERNET_DIAL_UNATTENDED','LongWord').SetUInt( $8000);
 CL.AddDelphiFunction('Function InternetHangUp( dwConnection : DWORD; dwReserved : DWORD) : DWORD');
 CL.AddConstantN('INTERENT_GOONLINE_REFRESH','LongWord').SetUInt( $00000001);
 CL.AddConstantN('INTERENT_GOONLINE_MASK','LongWord').SetUInt( $00000001);
 CL.AddDelphiFunction('Function InternetGoOnline( lpszURL : pchar; hwndParent : HWND; dwFlags : DWORD) : BOOL');
 CL.AddDelphiFunction('Function InternetAutodial( dwFlags : DWORD; dwReserved : DWORD) : BOOL');
 CL.AddConstantN('INTERNET_AUTODIAL_FORCE_ONLINE','LongInt').SetInt( 1);
 CL.AddConstantN('INTERNET_AUTODIAL_FORCE_UNATTENDED','LongInt').SetInt( 2);
 CL.AddConstantN('INTERNET_AUTODIAL_FAILIFSECURITYCHECK','LongInt').SetInt( 4);
 CL.AddDelphiFunction('Function InternetAutodialHangup( dwReserved : DWORD) : BOOL');
 CL.AddDelphiFunction('Function InternetGetConnectedState( lpdwFlags : DWORD; dwReserved : DWORD) : BOOL');
 CL.AddConstantN('INTERNET_CONNECTION_MODEM','LongInt').SetInt( 1);
 CL.AddConstantN('INTERNET_CONNECTION_LAN','LongInt').SetInt( 2);
 CL.AddConstantN('INTERNET_CONNECTION_PROXY','LongInt').SetInt( 4);
 CL.AddConstantN('INTERNET_CONNECTION_MODEM_BUSY','LongInt').SetInt( 8);
 CL.AddConstantN('INTERNET_RAS_INSTALLED','LongInt').SetInt( 16);
 CL.AddConstantN('INTERNET_CONNECTION_OFFLINE','LongInt').SetInt( 32);
 CL.AddConstantN('INTERNET_CONNECTION_CONFIGURED','LongInt').SetInt( 64);
 CL.AddConstantN('INTERNET_CUSTOMDIAL_CONNECT','LongInt').SetInt( 0);
 CL.AddConstantN('INTERNET_CUSTOMDIAL_UNATTENDED','LongInt').SetInt( 1);
 CL.AddConstantN('INTERNET_CUSTOMDIAL_DISCONNECT','LongInt').SetInt( 2);
 CL.AddConstantN('INTERNET_CUSTOMDIAL_SHOWOFFLINE','LongInt').SetInt( 4);
 CL.AddConstantN('INTERNET_CUSTOMDIAL_SAFE_FOR_UNATTENDED','LongInt').SetInt( 1);
 CL.AddConstantN('INTERNET_CUSTOMDIAL_WILL_SUPPLY_STATE','LongInt').SetInt( 2);
 CL.AddConstantN('INTERNET_CUSTOMDIAL_CAN_HANGUP','LongInt').SetInt( 4);
 CL.AddDelphiFunction('Function InternetSetDialState( lpszConnectoid : PChar; dwState : DWORD; dwReserved : DWORD) : BOOL');
end;

(* === run-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure RIRegister_WinInet_Routines(S: TPSExec);
begin
 S.RegisterDelphiFunction(@InternetTimeFromSystemTime, 'InternetTimeFromSystemTime', CdStdCall);
 S.RegisterDelphiFunction(@InternetCrackUrl, 'InternetCrackUrl', CdStdCall);
 S.RegisterDelphiFunction(@InternetCreateUrl, 'InternetCreateUrl', CdStdCall);
 S.RegisterDelphiFunction(@InternetCanonicalizeUrl, 'InternetCanonicalizeUrl', CdStdCall);
 S.RegisterDelphiFunction(@InternetCombineUrl, 'InternetCombineUrl', CdStdCall);
 S.RegisterDelphiFunction(@InternetOpen, 'InternetOpen', CdStdCall);
 S.RegisterDelphiFunction(@InternetOpen, 'InternetOpen2', CdStdCall);

 S.RegisterDelphiFunction(@InternetCloseHandle, 'InternetCloseHandle', CdStdCall);
 S.RegisterDelphiFunction(@InternetConnect, 'InternetConnect', CdStdCall);
 S.RegisterDelphiFunction(@InternetOpenUrl, 'InternetOpenUrl', CdStdCall);
 S.RegisterDelphiFunction(@InternetOpenUrl, 'InternetOpenUrl2', CdStdCall);

 S.RegisterDelphiFunction(@InternetReadFile, 'InternetReadFile', CdStdCall);
 //S.RegisterDelphiFunction(@InternetReadFileEx, 'InternetReadFileEx', CdStdCall);
 S.RegisterDelphiFunction(@InternetSetFilePointer, 'InternetSetFilePointer', CdStdCall);
 S.RegisterDelphiFunction(@InternetWriteFile, 'InternetWriteFile', CdStdCall);
 S.RegisterDelphiFunction(@InternetQueryDataAvailable, 'InternetQueryDataAvailable', CdStdCall);
 S.RegisterDelphiFunction(@InternetFindNextFile, 'InternetFindNextFile', CdStdCall);
 S.RegisterDelphiFunction(@InternetQueryOption, 'InternetQueryOption', CdStdCall);
 S.RegisterDelphiFunction(@InternetSetOption, 'InternetSetOption', CdStdCall);
 //S.RegisterDelphiFunction(@InternetSetOptionEx, 'InternetSetOptionEx', CdStdCall);
 S.RegisterDelphiFunction(@InternetLockRequestFile, 'InternetLockRequestFile', CdStdCall);
 S.RegisterDelphiFunction(@InternetUnlockRequestFile, 'InternetUnlockRequestFile', CdStdCall);
 S.RegisterDelphiFunction(@InternetGetLastResponseInfo, 'InternetGetLastResponseInfo', CdStdCall);
 //S.RegisterDelphiFunction(@InternetSetStatusCallback, 'InternetSetStatusCallback', CdStdCall);
 S.RegisterDelphiFunction(@FtpFindFirstFile, 'FtpFindFirstFile', CdStdCall);
 S.RegisterDelphiFunction(@FtpGetFile, 'WFtpGetFile', cdRegister);
 S.RegisterDelphiFunction(@FtpPutFile, 'WFtpPutFile', CdStdCall);
 S.RegisterDelphiFunction(@FtpDeleteFile, 'FtpDeleteFile', CdStdCall);
 S.RegisterDelphiFunction(@FtpRenameFile, 'FtpRenameFile', CdStdCall);
 S.RegisterDelphiFunction(@FtpOpenFile, 'FtpOpenFile', CdStdCall);
 S.RegisterDelphiFunction(@FtpCreateDirectory, 'FtpCreateDirectory', CdStdCall);
 S.RegisterDelphiFunction(@FtpRemoveDirectory, 'FtpRemoveDirectory', CdStdCall);
 S.RegisterDelphiFunction(@FtpSetCurrentDirectory, 'FtpSetCurrentDirectory', CdStdCall);
 S.RegisterDelphiFunction(@FtpGetCurrentDirectory, 'FtpGetCurrentDirectory', CdStdCall);
 S.RegisterDelphiFunction(@FtpCommand, 'FtpCommand', CdStdCall);
 S.RegisterDelphiFunction(@FtpGetFileSize, 'FtpGetFileSize', CdStdCall);
 S.RegisterDelphiFunction(@IS_GOPHER_FILE, 'IS_GOPHER_FILE', cdRegister);
 S.RegisterDelphiFunction(@IS_GOPHER_DIRECTORY, 'IS_GOPHER_DIRECTORY', cdRegister);
 S.RegisterDelphiFunction(@IS_GOPHER_PHONE_SERVER, 'IS_GOPHER_PHONE_SERVER', cdRegister);
 S.RegisterDelphiFunction(@IS_GOPHER_ERROR, 'IS_GOPHER_ERROR', cdRegister);
 S.RegisterDelphiFunction(@IS_GOPHER_INDEX_SERVER, 'IS_GOPHER_INDEX_SERVER', cdRegister);
 S.RegisterDelphiFunction(@IS_GOPHER_TELNET_SESSION, 'IS_GOPHER_TELNET_SESSION', cdRegister);
 S.RegisterDelphiFunction(@IS_GOPHER_BACKUP_SERVER, 'IS_GOPHER_BACKUP_SERVER', cdRegister);
 S.RegisterDelphiFunction(@IS_GOPHER_TN3270_SESSION, 'IS_GOPHER_TN3270_SESSION', cdRegister);
 S.RegisterDelphiFunction(@IS_GOPHER_ASK, 'IS_GOPHER_ASK', cdRegister);
 S.RegisterDelphiFunction(@IS_GOPHER_PLUS, 'IS_GOPHER_PLUS', cdRegister);
 S.RegisterDelphiFunction(@IS_GOPHER_TYPE_KNOWN, 'IS_GOPHER_TYPE_KNOWN', cdRegister);
 S.RegisterDelphiFunction(@GopherCreateLocator, 'GopherCreateLocator', CdStdCall);
 S.RegisterDelphiFunction(@GopherGetLocatorType, 'GopherGetLocatorType', CdStdCall);
 S.RegisterDelphiFunction(@GopherFindFirstFile, 'GopherFindFirstFile', CdStdCall);
 S.RegisterDelphiFunction(@GopherOpenFile, 'GopherOpenFile', CdStdCall);
 S.RegisterDelphiFunction(@GopherGetAttribute, 'GopherGetAttribute', CdStdCall);
 S.RegisterDelphiFunction(@HttpOpenRequest, 'HttpOpenRequest', CdStdCall);
 S.RegisterDelphiFunction(@HttpAddRequestHeaders, 'HttpAddRequestHeaders', CdStdCall);
 S.RegisterDelphiFunction(@HttpSendRequest, 'HttpSendRequest', CdStdCall);
 //S.RegisterDelphiFunction(@HttpSendRequestEx, 'HttpSendRequestEx', CdStdCall);
 S.RegisterDelphiFunction(@HttpEndRequest, 'HttpEndRequest', CdStdCall);
 S.RegisterDelphiFunction(@HttpQueryInfo, 'HttpQueryInfo', CdStdCall);
 S.RegisterDelphiFunction(@InternetSetCookie, 'InternetSetCookie', CdStdCall);
 S.RegisterDelphiFunction(@InternetGetCookie, 'InternetGetCookie', CdStdCall);
 S.RegisterDelphiFunction(@InternetAttemptConnect, 'InternetAttemptConnect', CdStdCall);
 S.RegisterDelphiFunction(@InternetCheckConnection, 'InternetCheckConnection', CdStdCall);
 //S.RegisterDelphiFunction(@InternetAuthNotifyCallback, 'InternetAuthNotifyCallback', CdStdCall);
 S.RegisterDelphiFunction(@InternetErrorDlg, 'InternetErrorDlg', CdStdCall);
 S.RegisterDelphiFunction(@InternetConfirmZoneCrossing, 'InternetConfirmZoneCrossing', CdStdCall);
 S.RegisterDelphiFunction(@CreateUrlCacheEntry, 'CreateUrlCacheEntry', CdStdCall);
 S.RegisterDelphiFunction(@CommitUrlCacheEntry, 'CommitUrlCacheEntry', CdStdCall);
 S.RegisterDelphiFunction(@RetrieveUrlCacheEntryFile, 'RetrieveUrlCacheEntryFile', CdStdCall);
 S.RegisterDelphiFunction(@UnlockUrlCacheEntryFile, 'UnlockUrlCacheEntryFile', CdStdCall);
 S.RegisterDelphiFunction(@RetrieveUrlCacheEntryStream, 'RetrieveUrlCacheEntryStream', CdStdCall);
 S.RegisterDelphiFunction(@ReadUrlCacheEntryStream, 'ReadUrlCacheEntryStream', CdStdCall);
 S.RegisterDelphiFunction(@UnlockUrlCacheEntryStream, 'UnlockUrlCacheEntryStream', CdStdCall);
 S.RegisterDelphiFunction(@GetUrlCacheEntryInfo, 'GetUrlCacheEntryInfo', CdStdCall);
 //S.RegisterDelphiFunction(@GetUrlCacheEntryInfoEx, 'GetUrlCacheEntryInfoEx', CdStdCall);
 S.RegisterDelphiFunction(@SetUrlCacheEntryInfo, 'SetUrlCacheEntryInfo', CdStdCall);
 S.RegisterDelphiFunction(@CreateUrlCacheGroup, 'CreateUrlCacheGroup', CdStdCall);
 S.RegisterDelphiFunction(@DeleteUrlCacheGroup, 'DeleteUrlCacheGroup', CdStdCall);
 S.RegisterDelphiFunction(@SetUrlCacheEntryGroup, 'SetUrlCacheEntryGroup', CdStdCall);
 //S.RegisterDelphiFunction(@FindFirstUrlCacheEntryEx, 'FindFirstUrlCacheEntryEx', CdStdCall);
 //S.RegisterDelphiFunction(@FindNextUrlCacheEntryEx, 'FindNextUrlCacheEntryEx', CdStdCall);
 S.RegisterDelphiFunction(@FindFirstUrlCacheEntry, 'FindFirstUrlCacheEntry', CdStdCall);
 S.RegisterDelphiFunction(@FindNextUrlCacheEntry, 'FindNextUrlCacheEntry', CdStdCall);
 S.RegisterDelphiFunction(@FindCloseUrlCache, 'FindCloseUrlCache', CdStdCall);
 S.RegisterDelphiFunction(@DeleteUrlCacheEntry, 'DeleteUrlCacheEntry', CdStdCall);
 S.RegisterDelphiFunction(@InternetDial, 'InternetDial', CdStdCall);
 S.RegisterDelphiFunction(@InternetHangUp, 'InternetHangUp', CdStdCall);
 S.RegisterDelphiFunction(@InternetGoOnline, 'InternetGoOnline', CdStdCall);
 S.RegisterDelphiFunction(@InternetAutodial, 'InternetAutodial', CdStdCall);
 S.RegisterDelphiFunction(@InternetAutodialHangup, 'InternetAutodialHangup', CdStdCall);
 S.RegisterDelphiFunction(@InternetGetConnectedState, 'InternetGetConnectedState', CdStdCall);
 S.RegisterDelphiFunction(@InternetSetDialState, 'InternetSetDialState', CdStdCall);
end;

 
 
{ TPSImport_WinInet }
(*----------------------------------------------------------------------------*)
procedure TPSImport_WinInet.CompileImport1(CompExec: TPSScript);
begin
  SIRegister_WinInet(CompExec.Comp);
end;
(*----------------------------------------------------------------------------*)
procedure TPSImport_WinInet.ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter);
begin
  //RIRegister_WinInet(ri);
  RIRegister_WinInet_Routines(CompExec.Exec); // comment it if no routines
end;
(*----------------------------------------------------------------------------*)
 
 
end.
