unit uPSI_PathFuncTest;
{
This file has been generated by UnitParser v0.7, written by M. Knight
and updated by NP. v/d Spek and George Birbilis. 
Source Code from Carlo Kok has been used to implement various sections of
UnitParser. Components of ROPS are used in the construction of UnitParser,
code implementing the class wrapper is taken from Carlo Kok's conv utility

}
interface
 
uses
   SysUtils
  ,Classes
  ,uPSComponent
  ,uPSRuntime
  ,uPSCompiler
  ;
 
type 
(*----------------------------------------------------------------------------*)
  TPSImport_PathFuncTest = class(TPSPlugin)
  protected
    procedure CompileImport1(CompExec: TPSScript); override;
    procedure ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter); override;
  end;
 
 
{ compile-time registration functions }
procedure SIRegister_PathFuncTest(CL: TPSPascalCompiler);

{ run-time registration functions }
procedure RIRegister_PathFuncTest_Routines(S: TPSExec);

procedure Register;

implementation


uses
   PathFuncTest
  ;
 
 
procedure Register;
begin
  RegisterComponents('Pascal Script', [TPSImport_PathFuncTest]);
end;

(* === compile-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure SIRegister_PathFuncTest(CL: TPSPascalCompiler);
begin
 CL.AddDelphiFunction('Procedure PathFuncRunTests( const AlsoTestJapaneseDBCS : Boolean)');
end;

(* === run-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure RIRegister_PathFuncTest_Routines(S: TPSExec);
begin
 S.RegisterDelphiFunction(@PathFuncRunTests, 'PathFuncRunTests', cdRegister);
end;

 
 
{ TPSImport_PathFuncTest }
(*----------------------------------------------------------------------------*)
procedure TPSImport_PathFuncTest.CompileImport1(CompExec: TPSScript);
begin
  SIRegister_PathFuncTest(CompExec.Comp);
end;
(*----------------------------------------------------------------------------*)
procedure TPSImport_PathFuncTest.ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter);
begin
  RIRegister_PathFuncTest(ri);
  RIRegister_PathFuncTest_Routines(CompExec.Exec); // comment it if no routines
end;
(*----------------------------------------------------------------------------*)
 
 
end.
